### ISSUE TITLE
Don't reimport scores with identical values

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1168]
As an instructor
When I import grades and the same grade exists for a student
Then that student should not receive a grade updated email
So that they are not confused

**Comment by jwright** [comment]
@chcholman Can you specify a description for this when you get a chance?

**Comment by chcholman** [comment]
Yes! When importing grade scores, if a student already has a grade for that assignment we should check to see if the score values are the same. If they are, no need to re-import that score (it triggers recalculating their total score, which hasn't been changed, and sends them an email about a new grade being released, when it's still the same).

**Comment by jwright** [comment]
@chcholman I assume we want to import the grade if the grade is the same but the feedback is different?

**Comment by chcholman** [comment]
@jwright Yup!

**Comment by jwright** [comment]
@chcholman Should the instructor see the grade as imported in the results?

**Comment by chcholman** [comment]
@jwright Should probably be a new category of "Already imported grades"?
