### ISSUE TITLE
Min and max group size validations error out on nil comparisons

### ISSUE THREAD

**Issue by zazaian** [UM-USElab/gradecraft-development#1211]
Course.rb
117: validates_numericality_of :max_group_size, :allow_nil => true, :greater_than_or_equal_to => 1
118: validates_numericality_of :min_group_size, :allow_nil => true, :greater_than_or_equal_to => 1

These need to be rewritten to not run the validation against nil or rescue it out. When max_group_size or min_group_size is nil the validation fails and throws an error.

https://github.com/UM-USElab/gradecraft-development/blob/master/app/models/course.rb
Current as of commit a878dae8b78ce736061bf078b14bbf2b425e25e9

**Comment by jwright** [comment]
@zazaian

I cannot replicate this issue. Here is the spec I wrote for this situation (I wrote the same one for `max_group_size` as well.

```
it "allows for a nil min group size" do
  subject.min_group_size = nil
  expect(subject).to be_valid
  expect(subject.errors[:min_group_size]).to be_empty
end
```

This passes and does not throw an exception.

I did some digging in the Rails source code and this line (https://github.com/rails/rails/blob/v4.2.3/activemodel/lib/active_model/validations/numericality.rb#L30) prevents the check for >= to happen.

Are we sure this was a result of the issue?

**Comment by zazaian** [comment]
I was also unable to replicate this. Searched loggly, rollbar and newrelic for min_group_size and max_group_size errors in the last two weeks and didn't find anything. @jwright added a spec for this case so it should be covered if it pops up in tests again, but we'll close it for now and keep an eye out for additional occurrences.
