### ISSUE TITLE
UM user import

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1230]
We need to be able to quickly import the roster of courses that are at UM. They should 1) know that these users are to be authenticated via Shibboleth, and so not create/trigger password creation process, and 2) mark as active immediately.

**Comment by chcholman** [comment]
For users who are authenticated via Shibboleth, we don't store passwords (they use the UM Login tab/button). When instructors want to import them, they will have a list of users either in the form of uniqname (cholma) or email (cholma@umich.edu). 

1. Whichever we get, we need to store the uniqname as the username,
2. and we need to store the uniqname + @umich.edu as their email 
3. We do not store a password for them (and should not trigger the password creation process)
4. We should automatically mark them as active
5. We should include the option to send students emails/not

Happy to clarify this further!

**Comment by jwright** [comment]
@chcholman What do you mean by #1 "Whichever we get"? We will always get a uniquename, correct? Or will we sometimes get the email and we just need to use the first part of that as their uniquename?

**Comment by chcholman** [comment]
Exactly - some people will have a roster that has emails and will try to upload those

**Comment by jwright** [comment]
@chcholman I am assuming we need some sort of option on the [users/import](http://localhost:5000/users/import) view that allows the staff to select that "This is a UM Login Import"? Do you know what that checkbox should say or how do you envision that UI?

**Comment by chcholman** [comment]
@jwright Yes, that makes total sense. "Use UM Authentication" should work as the checkbox label. 

I'm wondering if some of this shouldn't be a setting at the course level that defines which form you interact with - if we knew "This is a K-12 course that doesn't have email access" it would be one thing vs. a UM course, vs. an off-campus course. But maybe that's trying to be too smart, and we should let users decide. For now, the checkbox setting on the form should suffice.

**Comment by jwright** [comment]
@chcholman - I do like the course level setting. I can add that if you'd like. Let me know. My only hesitation is it becoming too restrictive. Can there be courses that can be off-campus courses that allow UM logins and GradeCraft logins?

**Comment by chcholman** [comment]
@jwright There's about to be a course on campus that allows both modes within the same course (students + alumni), so I guess that binary is going to get questioned really quickly. Let's let the user decide for the moment, I guess.

**Comment by jwright** [comment]
@chcholman What email are you referring to? The only user email we have is the one we send when they need to activate their account. Is this a new "welcome to GradeCraft" email?

**Comment by chcholman** [comment]
@jwright Nope, just the activation email.

**Comment by jwright** [comment]
@chcholman Ok. So #4 and #5 only occur if they choose to automatically activate the students?

**Comment by chcholman** [comment]
@jwright Yes, if they've selected to automatically activate students, then we are not sending them the account activation email.
