### ISSUE TITLE
Archiver checks for abandoned assets from failed archive attempts

### ISSUE THREAD

**Issue by zazaian** [UM-USElab/gradecraft-development#1267]
Archiver requests made for previously-failed archive attempts should check for the existence of an abandoned directory in /tmp matching the current request, and for any additional files built or fetched. This will prevent additional local system overhead as well as overhead from S3 in the event that archives fail to complete building.

**Comment by zazaian** [comment]
This is kind of the same as the other concern. I don't think there's going to be any issue re-building a few files in production. Might be worth revisiting if we're exporting files consistently and simultaneously for classes with 1000 students, and even then I'm not sure what kind of speed gains we'd actually see. What's the largest class we're working with right now @chcholman?

**Comment by chcholman** [comment]
@zazaian 550 is the largest class we've dealt with so far. We need to keep an eye on scale here because there's longstanding interest in using GC for a MOOC, but if we were to go that direction we're going to have to think out of the box regards to how we do assessment at all. Closing this for now.

**Comment by zazaian** [comment]
K, that's what I presumed. Again this is really only relevant if some kind
of failure occurs, so hopefully it would only be dealing with edge cases
anyway. We'll have to do some performance testing for the really-big
classes to see what kind of build times we're looking at for 500mb-1gb
exports.
