### ISSUE TITLE
Archiver removes temp directory only on successful S3 upload

### ISSUE THREAD

**Issue by zazaian** [UM-USElab/gradecraft-development#1268]
The archiver utility should remove the source files for the archive that have been assembled on the local disk, but only if it's been confirmed that the completed archive file has been successfully uploaded to S3 or its final destination. This will allow archiving attempts made by additional jobs to use abandoned temporary archive files, but will make entirely new attempts to assemble the requested archive data if the previous archive has been completed.

![archivephotos_01](https://cloud.githubusercontent.com/assets/95957/10828826/fac4490c-7e76-11e5-8b79-75c7d723af83.jpg)

**Comment by zazaian** [comment]
This probably isn't necessary anymore since the archive-building process is happening so quickly now that it really wouldn't buy us much in terms of value. Additionally it adds some complexity to the archiver workflow. For the moment job-retries for building an archive spawn a completely new temp dir and start over, though the same SubmissionsExport record is used to keep track of the archive output. We could implement this in the future though for the time being I'm not sure it'll earn us much.

@chcholman thoughts?

**Comment by chcholman** [comment]
@zazaian Let's close for now and iterate based on what we observe
