### ISSUE TITLE
Default badge icon route broken in production

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1277]

**Comment by jwright** [comment]
@chcholman Can you provide some detail/replication steps around this?

**Comment by chcholman** [comment]
@jwright We're getting lots of log messages like this when there's no badge icon uploaded: 

ActionController::RoutingError (No route matches [GET] "/assignments/1807/grade/%7B%7Bbadge.icon%7D%7D") 

If the badge has no image uploaded, we want to display the default image. That correctly appears (so far as I can tell), but it would be nice not to have the error output in the log.
