### ISSUE TITLE
If assignment types don't exist, exporting summary scores within the interface should not be possible

### ISSUE THREAD

**Issue by zazaian** [UM-USElab/gradecraft-development#1280]
nil-method error coming up in the submissions controller. Reported in this rollbar ticket:
https://rollbar.com/gradecraft/gradecraft-development/items/1303/

![image](https://cloud.githubusercontent.com/assets/95957/10851074/6cbb79ba-7f29-11e5-86fa-b70172a712be.png)

**Comment by chcholman** [comment]
Dug into this a little bit more - this happened because someone tried to export scores for a class that didn't have assignment types (or scores) yet. So it needs better error reporting, but is not really a bug.
