### ISSUE TITLE
Investigate touch: true calls

### ISSUE THREAD

**Issue by zazaian** [UM-USElab/gradecraft-development#1291]
At some point touch: true calls were added to a myriad of associations around the app, presumably in an attempt to trigger association updates for Russian doll caching.

However it doesn't seem that these were properly implemented, and they've been causing stack exception issues around Rubrics. It's possible that there are other errors occurring that we're missing, or even just unnecessary updates being performed throughout the stack. It might be worth going through and investigating/testing these to make sure there aren't any stray bugs, and removing them where sensible.

![touch_true](https://cloud.githubusercontent.com/assets/95957/10864009/c84a4a5c-7fdf-11e5-90f7-3a6768d79e37.jpg)

### egrep result for 'touch: true'
```bash
app/models/badge.rb:18:  belongs_to :course, touch: true
app/models/grade_scheme_element.rb:4:  belongs_to :course, touch: true
app/models/assignment.rb:17:  belongs_to :course, touch: true
app/models/assignment.rb:18:  belongs_to :assignment_type, -> { order('position ASC') }, touch: true
app/models/submission.rb:9:  belongs_to :task, touch: true
app/models/submission.rb:10:  belongs_to :assignment, touch: true
app/models/submission.rb:11:  belongs_to :student, :class_name => 'User', touch: true
app/models/submission.rb:12:  belongs_to :creator, :class_name => 'User', touch: true
app/models/submission.rb:13:  belongs_to :group, touch: true
app/models/submission.rb:14:  belongs_to :course, touch: true
app/models/grade.rb:21:  belongs_to :course, touch: true
app/models/grade.rb:22:  belongs_to :assignment, touch: true
app/models/grade.rb:23:  belongs_to :assignment_type, touch: true
app/models/grade.rb:24:  belongs_to :student, :class_name => 'User', touch: true
app/models/grade.rb:25:  belongs_to :team, touch: true
app/models/grade.rb:27:  belongs_to :task, touch: true # Optional
app/models/grade.rb:28:  belongs_to :group, :polymorphic => true, touch: true # Optional
app/models/grade.rb:29:  belongs_to :graded_by, class_name: 'User', touch: true
app/models/earned_badge.rb:8:  belongs_to :course, touch: true
app/models/earned_badge.rb:10:  belongs_to :student, :class_name => 'User', touch: true
app/models/challenge.rb:14:  belongs_to :course, touch: true
app/models/team.rb:11:  belongs_to :course, touch: true
app/models/course_membership.rb:2:  belongs_to :course, touch: true
app/models/course_membership.rb:3:  belongs_to :user, touch: true
app/models/assignment_weight.rb:6:  belongs_to :student, :class_name => 'User', touch: true
app/models/assignment_weight.rb:8:  belongs_to :assignment, touch: true
app/models/event.rb:7:  belongs_to :course, touch: true
app/models/assignment_type.rb:6:  belongs_to :course, touch: true
app/models/user.rb:75:  belongs_to :default_course, :class_name => 'Course', touch: true
```

**Comment by chcholman** [comment]
The places where touch: true has been added: 

*Assignment* 
belongs_to :course, touch: true

*Assignment Type* 
belongs_to :course, touch: true

*Assignment Weight*
belongs_to :student, :class_name => 'User', touch: true
belongs_to :assignment, touch: true

*Badge*
belongs_to :course, touch: true

*Course Membership *
belongs_to :course, touch: true
belongs_to :user, touch: true

*Earned Badge* 
belongs_to :course, touch: true
belongs_to :student, :class_name => 'User', touch: true

*Event* 
belongs_to :course, touch: true

*Grade*
belongs_to :course, touch: true
belongs_to :assignment, touch: true
belongs_to :assignment_type, touch: true
belongs_to :student, :class_name => 'User', touch: true
 belongs_to :team, touch: true
belongs_to :task, touch: true # Optional
belongs_to :group, :polymorphic => true, touch: true # Optional
belongs_to :graded_by, class_name: 'User', touch: true

*Grade Scheme Element*
belongs_to :course, touch: true

*Submission*
belongs_to :task, touch: true
belongs_to :assignment, touch: true
belongs_to :student, :class_name => 'User', touch: true
belongs_to :creator, :class_name => 'User', touch: true
belongs_to :group, touch: true
belongs_to :course, touch: true

*Team*
belongs_to :course, touch: true

*User* 
belongs_to :default_course, :class_name => 'Course', touch: true
