### ISSUE TITLE
AssignmentPresenter#rubric_available? not returning correct value

### ISSUE THREAD

**Issue by zazaian** [UM-USElab/gradecraft-development#1293]
The #rubric_available? call on the assignment presenter isn't returning the correct value after a rubric has been designed and actually has metrics. My guess is that the use_rubric boolean on assignment isn't being updated correctly, but this needs further investigation.

```ruby
  def rubric_available?
    assignment.use_rubric? && !assignment.rubric.nil? && assignment.rubric.designed?
  end
```

![image](https://cloud.githubusercontent.com/assets/95957/10864098/d18c5e0e-7fe2-11e5-9808-4f9660f183d8.png)

**Comment by jwright** [comment]
@zazaian What view are you seeing issues with? 

I looked into the old view code in a few places and compared that with the `AssignmentPresenter#rubric_available?`. Here is what I replaced:

```
  # old view code from app/views/assignments/_buttons.html.haml
  ! ( @assignment.rubric and @assignment.rubric.designed? and @assignment.use_rubric? )
```

```
  # new presenter code
def rubric_available?
    assignment.use_rubric? && !assignment.rubric.nil? && assignment.rubric.designed?
  end

!presenter.rubric_available?
```

**Comment by jwright** [comment]
@zazaian I do see this difference: https://github.com/UM-USElab/gradecraft-development/commit/e1e9d6a9feb27a6a0e2b1a7545ea9cfd9f3a51cb#diff-a66aa0119d6001ac4f8551e22964ce6bL31

In this case, the old code does not check `Assignment#use_rubric?`. Is that supposed to be checked? Do you know when we would have a designed rubric but the assignment was not set up to use the rubric?

cc: @chcholman
