### ISSUE TITLE
Multiplied Gradebook

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1304]
We have most of the elements in place to export a multiplied gradebook...but we don't actually do it. We need to add an item to the left hand nav for courses where assignment_weighting is used, and send it to the instructor as needed.

**Comment by chcholman** [comment]
Tasks to complete: 

1) Remove the raw score value from the export:
https://github.com/UM-USElab/gradecraft-development/blob/master/app/models/course.rb#L460

2) Build mailer/exporter to send multiplied gradebook

3) Add link to staff navigation sidebar to export gradebook IF course .student_weighted? is true

**Comment by jwright** [comment]
@chcholman Can you explain what a multiplied gradebook is and what it is used for by the instructors?

**Comment by chcholman** [comment]
In some of our courses, students assign weights to specific assignment categories, thereby changing the points they earn for this work. So for a recent course I have the ability to select between essays, an exam, or writing a piece of code, and whichever I choose to weight gets double the amount of points. The others I earn the same, standard value for.  The gradebook export currently only includes raw scores (so if I earned 3000/4000 points for an assignment, and I weighted it double, then the raw_score I earned is 3000 but my score is 6000). We need a multiplied gradebook option that exports scores rather than raw scores for analytics and accounting purposes.

**Comment by jwright** [comment]
@chcholman Thank you! This helps out a lot.

For #3 above, should the instructor have the option to export both the "Full Gradebook" and a "Multiplied Gradebook" if the course allows for it? Or should they just have the "Multiplied Gradebook" option if the course is student weighted?

**Comment by chcholman** [comment]
@jwright 
The normal one should stay as well!
