### ISSUE TITLE
Add course numbers to search field for courses

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1347]

**Comment by chcholman** [comment]
Should also display the semester/year in the results - it's super hard to tell the difference between courses that run multiple times!

**Comment by jwright** [comment]
@chcholman Is this request referring to the search results from the drop down when being searched?

**Comment by chcholman** [comment]
Yup! I want to be able to search for 'GC101' and get related results (In addition to seeing them in the list). It's common that I know and refer to course numbers rather than names.

**Comment by jwright** [comment]
- [ ] Add the ability to search by course number
- [ ] Display course number in results
- [ ] Display semester/year in results
