### ISSUE TITLE
Disable update selected grade status if no grades selected to release

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1371]
Grading Status page:

<img width="740" alt="screen shot 2015-11-15 at 2 39 11 pm" src="https://cloud.githubusercontent.com/assets/234276/11170592/f237687c-8ba6-11e5-9fd1-c8d379d5f4f8.png">

**Comment by jwright** [comment]
@chcholman Do you know what route/url this is at?

**Comment by jwright** [comment]
@chcholman Nevermind :)

http://localhost:5000/grading_status

**Comment by chcholman** [comment]
There'll be a second place we need to do the same for each assignment, this route should be right (You need to add some grades - I'll make sure that happens in the next round of sample data): 

http://localhost:5000/assignments/37
