### ISSUE TITLE
Default date overriding selected year in Course Edit form

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1376]

**Comment by jwright** [comment]
@chcholman Can you expand a bit on this bug? Are you saying that a staff member is selecting a new year from the dropdown but the default is overriding the selected value?

**Comment by jwright** [comment]
@chcholman I believe I see the issue. Are these the replication steps?

1. Staff member edits a course
1. Staff member updates the course year to a different year other than the current year
1. Clicks update
1. Show view displays the newly updated year
1. Click edit
1. Notice that the year displayed in the edit view is the current year again

**Comment by chcholman** [comment]
@jwright Yup, that's exactly it. So we want the default year to be this year if they haven't yet entered on, but we want it to select the actual year they've entered if it's present
