### ISSUE TITLE
Refactor & test SubmissionsController

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1382]

**Comment by jwright** [comment]
Current grade: F
Current coverage: 70%

**Comment by jwright** [comment]
@chcholman Currently the Submissions#index action just redirects back to the assignments show route. I checked the app for use of the path and it does not exist. Do you mind if I just remove this action and route? I wanted to ensure it was not needed for some reason.

**Comment by chcholman** [comment]
@jwright Yes, totally fine to remove the action. We do see a fair number of people hacking the URLs (assuming that they're quite predictable and that you can navigate around that way, and often they're right), so I'd be curious what the best practice is send them somewhere more useful than just an error message.
