### ISSUE TITLE
Update Resque's method of error handling

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1413]
Log output: WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.

**Comment by jwright** [comment]
@chcholman What issues are we seeing where this is needed? What issue is this trying to solve?

**Comment by chcholman** [comment]
@jwright If you look at the console log after starting foreman, you'll see this: 

resque_worker.1    | WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.

**Comment by jwright** [comment]
@chcholman Thank you!
