### ISSUE TITLE
Update internal importer so it sets kerberos_uid to username

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1460]

**Comment by jwright** [comment]
@chcholman Do you have a specific import file that this is not working for so I can test it? 

This *should* be working with this specific logic: https://github.com/UM-USElab/gradecraft-development/blob/master/app/services/creates_new_user/generates_usernames.rb#L14 

My guess is that they do not have a umich.edu email address or something I am not accounting for.

**Comment by chcholman** [comment]
@jwright You're right, it's working! Thanks/sorry!
