### ISSUE TITLE
Add item count number to Instructor nav bar

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1504]
The grading status, resubmissions, and ungraded links in the left hand nav should all be bolded and display a number of items to manage that reflect how many elements exist on each page to address

**Comment by jwright** [comment]
- [ ] Grading status display status
- [ ] Resubmissions display status
- [ ] Ungraded display status

**Comment by jwright** [comment]
@chcholman What do you think of this style? Just a few overridden styles from the announcements for a student.

![screen shot 2016-01-27 at 12 47 35 pm](https://cloud.githubusercontent.com/assets/35017/12622632/469c49d8-c4f4-11e5-9a8e-dbd75fc0e63c.png)

**Comment by jwright** [comment]
@chcholman Is the `Grading status` count a sum of unreleased grades, ungraded submissions, and in progress grades?

**Comment by chcholman** [comment]
Yes!
