### ISSUE TITLE
Exclude grade

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1520]
Instructors occasionally want for a grade to not be counted towards a student's total score. Interaction: switch on the assignment index/student syllabus page that allows you to turn a grade to "off" or "muted", thereby not counting towards the student's total grade.

**Comment by jwright** [comment]
@chcholman I assume this is only an operation that staff members can perform?

**Comment by chcholman** [comment]
@jwright Most definitely!

**Comment by jwright** [comment]
- [ ] Add "mute" button on `/assignments`
- [ ] Add "mute" button on `/assignments/:id/edit`
- [ ] Add "mute" button on `/students/syllabus?student_id=X`

**Comment by jwright** [comment]
@chcholman Are we using the terminology of "mute" in the UI for what this does?

**Comment by jwright** [comment]
@chcholman In addition, is this an all or nothing type of thing for all students assigned to the assignment?

**Comment by chcholman** [comment]
@jwright Just doing a quick confirmation about terminology, and will get back to you shortly. No, it's definitely not about all students - only ever specific students.

**Comment by jwright** [comment]
@chcholman Great, thanks for the clarification. I will put this setting on the grade then. Instructors will be able to select various "mute" settings for specific students.

**Comment by jwright** [comment]
@chcholman One more clarification. Can group grades or rubric grades be muted?

**Comment by chcholman** [comment]
@jwright Rubric grades - yes, but that would not mean that anything was overridden at the criteria level, just the grade that's produced. Group grades - yes as well, but at a specific student level. Since group grading creates individual grades, I want to be able to mute it for just one student in the group.
