### ISSUE TITLE
Grading Submission Revisions

### ISSUE THREAD

**Issue by jwright** [UM-USElab/gradecraft-development#1533]
As a professor
When I assign a grade to a submission
Then that grade should be for that specific submission revision
So that I can grade other revisions later

**Comment by jwright** [comment]
Related to #875

**Comment by jwright** [comment]
@chcholman How do we want to show this in the UI? Should we just show it on the submission history? Should we implement a UI like we talked about in Slack (e.g. Basecamp history)?

**Comment by chcholman** [comment]
@jwright The tree history is quite cool, but it can even be a little bit simpler: 

Assignment 1
Submitted January 20, 2016, 10:15PM
* file attachment.pdf
Score: 80
Feedback:  [ text feedback ]
Rubric Grade: [grid]
--
Resubmitted Feb 1, 2016, 8:42AM
* revised file-attachment.pdf
Score: 95
Feedback: [feedback]
Rubric grade if present

I am wondering about 1) showing it in reverse order (but not convinced) and 2) highlighting difference ("You earned 15 more points than your first submission")

**Comment by jwright** [comment]
@chcholman Is this partial going to replace what is currently in the submission history tab when showing a submission?

**Comment by chcholman** [comment]
@jwright That would be ideal - to show them in a unified manner.

**Comment by jwright** [comment]
- [ ] Only show grade event if raw score or feedback were updated (raw score, state, or feedback)
- [ ] Make sure grade event is not shown if displaying to students and the grade is not visible
- [ ] Change sentence for when the field changes from nil
- [ ] Do not put quotes around integers in sentence
- [ ] Remove date from content
- [ ] Students do not need to see state changes on grades
- [ ] Fix css so that it only affects the timeline
