### ISSUE TITLE
Create new course membership if user already exists

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1581]
As an instructor
When I add student to my class that exists in another class I do not have access to
Then I should be able to create a new course membership for them for my course
And return a success notification

**Comment by jwright** [comment]
@chcholman This functionality is already available "manually". Do we want to make this the default instead of having the instructor click on it?

<img width="1246" alt="screen_shot_2016-01-24_at_8_50_03_am" src="https://cloud.githubusercontent.com/assets/35017/12536594/c3418ad6-c277-11e5-954b-29aadf908694.png">

**Comment by chcholman** [comment]
@jwright It is, but it requires that I know what course that user is currently in to find them and then have access to edit them. What we need to add for this is the ability for any instructor to (find or) create new users - for instance if you look at this screenshot, McGonagall has an account already, if I'm in the context of a course she *doesn't* have access to and try to add her to this one, I see this: 

<img width="944" alt="screen shot 2016-01-24 at 9 38 00 am" src="https://cloud.githubusercontent.com/assets/234276/12536818/7f124f2e-c27e-11e5-84c5-4397414daf74.png">

**Comment by jwright** [comment]
@chcholman Thank you for the clarification! I got it now.

**Comment by jwright** [comment]
@chcholman What do we do with this use case?

- Email exists but the first name, last name, or display name are different from the current values?

Do we change them? Do we update them in the view and let the instructor know? Do we just ignore the new values?

**Comment by chcholman** [comment]
@jwright Update them and let the instructor know

**Comment by jwright** [comment]
@chcholman I just wanted to verify. You want to update the existing user with the new names and notify the existing instructor that the values changed?

**Comment by jwright** [comment]
@chcholman I started looking at this a bit and the controller would have to expand a lot or the service would have to be adjusted and not really make sense. The controller is for "creating a user" and it would have to expand into "creating or updating a user". 

I played around with this work flow a little and I wanted to know what you thought about this:

![screen shot 2016-01-26 at 7 05 26 am](https://cloud.githubusercontent.com/assets/35017/12580201/9aa0c2a6-c3fb-11e5-8431-9942caf891cd.png)

Obviously, the "warning dialog" needs some style adjustment but I wanted to see what you thought about this. Should the professor/admin even be concerned that the user already exists?

**Comment by chcholman** [comment]
@jwright I appreciate the inclination to keep the actions separate and clean, but I'm not in love with the workflow it produces - there's no instance where the person who is adding the user would want to say no, so we're just adding an additional click and forcing them to deal with more information/steps.
