### ISSUE TITLE
Don't strip out links in description fields

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1597]
When instructors and students add description content we strip links from it, and should not.

**Comment by jwright** [comment]
@chcholman Is this in reference to the submission entry form?

**Comment by jwright** [comment]
@chcholman We currently sanitize the following:

- `Assignment#description`
- `Grade#feedback`
- `Group#text_proposal`
- `Submission#text_comment`

All of these have links stripped out.

**Comment by jwright** [comment]
@chcholman Actually, only the `Submission#text_comment` has links stripped out. It's the only one that uses the [`RESTRICTED` config](https://github.com/rgrove/sanitize#sanitizeconfigrestricted). Everything else uses the [`BASIC` config](https://github.com/rgrove/sanitize#sanitizeconfigbasic)

**Comment by chcholman** [comment]
@jwright Huh, interesting. I just got a bug report from an instructor that her links were being stripped out in the 'Assignment#description', but have tested locally that that's not happening (as you noted). I'll follow up with her.  

In the meantime, yes, we should allow links to come in through the 'Submission#text_comment' field. Thanks!

**Comment by jwright** [comment]
@chcholman In addition, I think we should try and eliminate the image and table ability within the rich text editors since those get striped out everywhere. Thoughts?

**Comment by chcholman** [comment]
@jwright Could we do the reverse and allow them? :grin:

**Comment by jwright** [comment]
@chcholman We could for sure. Is there anything that we should sanitize then? This is what we are currently sanitizing (I agree with the nofollow thing):

https://github.com/rgrove/sanitize#sanitizeconfigbasic
