### ISSUE TITLE
Timezone Management

### ISSUE THREAD

**Issue by zazaian** [UM-USElab/gradecraft-development#1599]
Hey @acousticrobot @jwright humons:

So I discussed with Cait the idea of adding a default timezone to users, and to use that in the interest of generating a user-visible timestamp that the user can adjust based on their user preferences. For now that would default to EST/Detroit time.

Does that sound like a good approach moving forward? Any thoughts/amendments? I'm going to put this in for generating timestamps on the submissions exports for the time being, and we can change/expand it in a future PR if that feels clever.

![image](https://cloud.githubusercontent.com/assets/95957/12653786/0f89ed12-c5bf-11e5-90e6-93f3462f073c.png)

**Comment by zazaian** [comment]
Actually, as I look at this it seems like it would make more sense to store the timezone on the course rather than the user, since it seems like we're more interested in standardizing the course experience than than the specific user experience. Also in instances where, for example, we were to eventually build out some kind of course feature for a MOOC scenario and had, theoretically, professors and GSIs in multiple regions, we'd likely want to generate data relative to course time rather than user time.

@chcholman thoughts?

**Comment by chcholman** [comment]
@zazaian I think that instance is a great example of what we want to build around - and that in that instance, you'd probably need a timezone on both the course and the user, in order to show the user the due date for an assignment in the time zone that matches to their situation. Does that make sense?

**Comment by zazaian** [comment]
@chcholman: yup, that definitely makes sense. I'll add a timezone to courses now, for the time being and use that for the export timestamps instead of user time.
