### ISSUE TITLE
Removing uploads needs to updated to AWS SDK2

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1605]

**Comment by zazaian** [comment]
@chcholman this is done but needs to be tested on staging since we're not currently running development files through S3. We can deploy this and test it whenever you'd like.

**Comment by chcholman** [comment]
@zazaian Great, thanks!

I've got work in staging that is being reviewed, so let's not post it there just yet. If you're ready, submit it as a PR and assign it to either Jamie or Jonathan for review. Else, after 5PM EST you can post it to staging.
