### ISSUE TITLE
Badges not awarding from within grade form

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1610]

**Comment by jwright** [comment]
@chcholman Is the issue that the badges are not appearing in the "Awarded Badges" area when they are clicked on?

**Comment by chcholman** [comment]
@jwright Yes

**Comment by jwright** [comment]
@chcholman Sorry. It's me again.

Should the badge be student visible when it is awarded?

**Comment by chcholman** [comment]
@jwright Geez, this guy. 

It should depend on the grade's status - if it's student visible, then the badge is too. If it's not yet released (and needs to be) then it's not student visible.

**Comment by jwright** [comment]
@chcholman Ok. There is no logic touching the student visible flag and so the student does not see the badge when they are awarded it. I will update that as well.

**Comment by chcholman** [comment]
@jwright Thanks :/
