### ISSUE TITLE
LTI Certification

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1633]
We have built a functional implementation of LTI 1.1, but we've never completed the certification tests. The test suite is here:
https://www.imsglobal.org/lti-certification-suite

The piece that we're missing are various error responses to handle every condition the spec requires. This task is to go through the test suite, add the necessary errors in response, and to suggest/do any cleanup of the current implementation if necessary.

**Comment by jonathoy** [comment]
Some Test Suite Results:

Test 4.5: Launch as user with no context role
- Status: Failure
- Expected result: User should be given whatever privileges are appropriate to a user with no role, which could be that they are denied access
- Observed result: User is assumed to be a student
- Action: Present user with a message stating that they should be granted a role in the course

Test 4.6: Launch as a user with an institution role but no context role
- Status: Needs Further Investigation
- Expected result: User should be given privileges appropriate to a user with no context role, which could be that they are denied access
- Observed result: 500 Internal Server Error
- Action: Investigate and possibly implement institution roles: https://www.imsglobal.org/specs/ltiv1p0/implementation-guide#toc-19

Test 4.7: Launch as a user with an institution role which has no corresponding context role 
- Status: Needs Further Investigation
- Expected result: User should be given privileges appropriate to a user with no context role, which could be that they are denied access
- Observed result: 500 Internal Server Error
- Action: See Test 4.6

**Comment by jonathoy** [comment]
Per our discussion, we will not be pursuing LTI 1.1 certification since our grading structure does not align with the way that LTI expects grades. Since it appears that LTI 1.2 certification requires the implementation of simple outcomes as in LTI 1.1, we will likely be aiming for LTI 1.0 certification.

**Comment by chcholman** [comment]
@jonathoy Emailed for a consultation on this 1/30, will let you know as soon as I've got something scheduled.
