### ISSUE TITLE
Attached Files Should Use Download Route, Not Presigned URL

### ISSUE THREAD

**Issue by zazaian** [UM-USElab/gradecraft-development#1634]
I'm looking at the form for viewing submission files etc, and currently we're using the presigned_url function from S3 to generate urls for every link on the page. The problem with this is that a) these urls are public, and b) they're generated every time any page with attachment files are loaded.

A better way to do this would be for the link to route to a download action for that particular file/asset, and then for the rails controller to stream the file from S3 via send_data to the user's browser. This would be faster, more secure, and would stop generating all of the presigned URLs which, while secure in and of themselves, really don't need to be generated at all.

@chcholman does this feel like a priority to you?

**Comment by chcholman** [comment]
@zazaian It's a priority, but probably not the next priority to address.

**Comment by zazaian** [comment]
Sounds good, just wanted to put this out there. They expire after a week anyway, but every time a page is loaded it generates a completely new batch of urls, so there could be hundreds available for any given submission. Just a heads up.
