### ISSUE TITLE
Incorporate Submission File history into Submission

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1647]
As a user, when I'm looking at submission histories, Submission files and Submissions are currently displayed as separate items. Since from the user's perspective they're functionally the same, they should be displayed as a single node - so if I've created a new Submission with a file attachment, that would produce one "Submission Created" node rather two nodes ("Submission Created' and "Submission File Created").

**Comment by jwright** [comment]
- [ ] Ignore submission file created events
- [ ] Change when a submission file is created and a previous one existed to say submission filename changed from x to y
- [ ] Place that change on a Submission Updated event

**Comment by jwright** [comment]
When a submission file changeset exists, create an entry in the associated submission change (by transaction id) to say "uploaded #{filename}".

**Comment by jwright** [comment]
- [ ] Add a `transform` method to `HistoryFilter` to transform any `SubmissionFile` create changeset to say it's an update with the filename (as above)

**Comment by jwright** [comment]
- [ ] Add a `merge` method to the `HistoryFilter` to add the `SubmissionFile` changeset to the `Submission` changeset with the same transaction id

**Comment by jwright** [comment]
@chcholman I just wanted to let you know that this may take a bit of time to implement since the displaying of this was originally only supposed to work with individual changesets. I think I have an idea on how to implement it but it may take some trial and error

**Comment by chcholman** [comment]
@jwright Totally fine - makes sense, is important, and will be extensible to other places where we need to track things (think resubmissions and highlight grade changes that reflect criterion outcome changes).
