### ISSUE TITLE
#last_login_at being called on nil CourseMembership

### ISSUE THREAD

**Issue by zazaian** [UM-USElab/gradecraft-development#1720]
We're getting instances in which `#last_login_at` is being called on `nil`in the `LoginEventPerformer` in the event that no `CourseMembership` is found for the login. I'll have to look further into where these records would be enqueued in the first place, but for now it's probably best just to fix the bug and only call `#last_login_at` if a `CourseMembership` is found.

**Comment by zazaian** [comment]
https://rpm.newrelic.com/accounts/367828/applications/2116987/traced_errors/e33450-3ba5fa5f-dff6-11e5-a1e3-b82a72d22a14

**Comment by zazaian** [comment]
@chcholman I have a patch for this immediate issue with `nil` being called on `CourseMembership`, but I want to look into how logins could occur in the system without a `course_id` or `user_id` being saved in the session in the first place.

I'll take a closer look at this tomorrow morning. In the meantime you can see the patch I've started on branch ` 1720-nil_course_membership_error `.

**Comment by chcholman** [comment]
@zazaian thanks
