### ISSUE TITLE
Deleting a course membership is not properly deleting a team membership

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1738]
We're seeing a bug when an instructor cancels a course membership, where the team memberships associated should be deleted, but aren't, thus causing a later bug regarding team scores attempting to include a nil value in a calculation.

**Comment by jwright** [comment]
@chcholman I cannot replicate this error and the code looks correct. Do you have any data examples on production I can take a look at?

**Comment by chcholman** [comment]
@jwright I don't at the moment. I am going to unassign you to this item, but leave it open and in the backlog as a known bug.
