### ISSUE TITLE
Integrate grade and badge feedback into announcement notifications

### ISSUE THREAD

**Issue by mariehooper** [UM-USElab/gradecraft-development#1778]
When any notification is sent to a user, it should be recorded within the app, and available to view for the user. Just like announcements, we should record if it has been viewed and when.

**Comment by jwright** [comment]
@cait Currently when an announcement is created by an admin, they get an email. I assume that when a Grade is released, the student should not receive both a "grade released" email and a "new announcement" email. They should only receive a "grade released" email. Is that correct?

**Comment by chcholman** [comment]
@jwright Yes!
