### ISSUE TITLE
Descriptions for assignment terminology - student onboarding panels

### ISSUE THREAD

**Issue by mariehooper** [UM-USElab/gradecraft-development#1879]
Student mentioned it was confusing for assignments/projects to be named different things (i.e. quests). Add description or "key" for this somewhere that describes how things are named in class.

**Comment by chcholman** [comment]
This should take the form of instructors declaring at the course level what each of the custom terms mean. If these descriptions exist, they should then be shown back to students on their dashboard (sketches to come).

**Comment by mariehooper** [comment]
@chcholman - should this appear in "Course Rules" or should we make this a separate module on the dashboard for courses that use this different terminology?

**Comment by chcholman** [comment]
@mariehooper I'm leaning towards it being part of Course Rules, but I'm open to another solution. What do you think?
