### ISSUE TITLE
Record the Grade Modifier

### ISSUE THREAD

**Issue by jwright** [UM-USElab/gradecraft-development#1970]
As an administrator
I would like to know who modified a grade
So that I can see if it's a student (student logged) or a faculty member

**Comment by jwright** [comment]
- [ ] Replace `instructor_modified` with `modified_by_id`
- [ ] Treat a non-nil `modified_by_id` as a `instructor_modified` true flag
- [ ] What do we do with the current data? Use the `graded_by_id`?

**Comment by chcholman** [comment]
@jwright it might be worth migrating the graded_by_id over tot he modified_by_id, so that we can drop the field

**Comment by jwright** [comment]
@chcholman How do you feel about keeping `graded_by_id` instead of using `modified_by_id`? I think it is more descriptive.

**Comment by jwright** [comment]
@chcholman Also, should that field (`graded_by_id` or `modified_by_id`) get updated if a student grade's themselves?

**Comment by chcholman** [comment]
@jwright I'm agree that `graded_by_id` is more descriptive and am fine with it staying. If it's updated by the student themselves, then it should record the student's own id.
