### ISSUE TITLE
Auto-award badges

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1998]
As an instructor, I want to be able to auto-award badges based on different student behaviors. To start with: 

- earning a number of points in the course overall
- submitting an assignment
- getting a particular grade on an assignment
- reading your feedback on an assignment
- earning a set number of points in an assignment type
- earning x set of badges (identified)
- earning N number of badges (count, not identified)

We'd also like to create a set that are default-created with every course (but the instructor can delete). We'll create custom graphics for these. They'll be for:  
- count of page loads in a course
- count of predictions made in a course
- first to submit an assignment

**Comment by jwright** [comment]
Notes to self:
--------------

Badges can be awarded on `Grade`, `Student`, and `Prediction`. 

I am envisioning a job that get's fired off which fires off the `CreatesEarnedBadge` service when certain criteria are met. Criteria can be defined as procs that are registered that could work something like this:

```
class SubmittingAssignmentBadge
  def badge
    Badge.find_by(name: "Submitting an Assignment", automatic: true)
  end

  def awardable?(student, grade, prediction)
    grade.submission.submitted_by? student
  end
end
```

All of the auto badges could be checked within the job and each one that is awardable are then created as earned badges.

**Comment by jwright** [comment]
Questions:

1. Can names be unique for badge/course?
1. Can names be changed for auto-badges?
1. If so, can we store an identifier that is not shown in the db so we can find the badge within the auto-award logic?

**Comment by chcholman** [comment]
Badges always belong to a particular course, so while their names aren't unique (within the course, or across the app) they should always be findable within the auto-award logic. Not entirely sure which name you're referring to being changed - the name of the badge being auto-awarded could change, yes. An earned badge doesn't have it's own name though - it references back to the badge's name. 

I think the `badge.id` is the right identifier here? What am I missing?
