### ISSUE TITLE
Rename Showtime::Presenter to Presenter::Base

### ISSUE THREAD

**Issue by zazaian** [UM-USElab/gradecraft-development#2045]
Showtime is a cute name for a presenter but we really shouldn't be using fancy names in `/lib` unless we're pulling in actual third-party libraries. In instances of built-for-gradecraft code in lib we should be using straightforward names to identify what each class or module is doing.

Later, if we decide to publicize these, Showtime is a great name for marketing the library within the Ruby ecosystem, but for now using proprietary names rather than clear ones is an antipattern.

**Comment by chcholman** [comment]
@zazaian I'm going to close this ticket for now, as I think the name is fine and we have lots of other things to do!

**Comment by zazaian** [comment]
Okay, we should probably put this back in later though. This is the only module in the entire `/lib` directory without a name that overtly describes its purpose.
