### ISSUE TITLE
Add Campus Techology award to awards page

### ISSUE THREAD

**Issue by ksofa2** [UM-USElab/gradecraft-development#2082]
https://campustechnology.com/innovators This is the best link I could find. Will they do a more specific write up for GC? Should we wait for that?

**Comment by chcholman** [comment]
@ksofa2 We think there's an additional article about GC coming, but this is probably the best link for the award announcement!

**Comment by ksofa2** [comment]
@chcholman Sounds good. Let's start with this one, and perhaps update the link in the future?

**Comment by chcholman** [comment]
@ksofa Awesome!

**Comment by chcholman** [comment]
Should say: 

"2016 Campus Technology Innovator (Teaching & Learning)" 
and link to:
https://campustechnology.com/articles/2016/06/01/press-release-campus-technology-announces-2016-innovators-award-honorees.aspx
