### ISSUE TITLE
External link helper balks at mailto links

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#2095]
Use case: a student submits an assignment with an email link in it. Currently the app fails to render the show view for the submission altogether.

**Comment by jwright** [comment]
@chcholman Can you give me an example of the link? Currently the links in the submission link cannot be email addresses so I am confused as to how they can make links for an email address.

**Comment by chcholman** [comment]
@jwright Not the submission link - links included in the submission comment. Does that make sense? I can email you an example of a submission that triggers the bug if it would help.

**Comment by jwright** [comment]
@chcholman I got it. Thanks!
