### ISSUE TITLE
Import Canvas assignment

### ISSUE THREAD

**Issue by ksofa2** [UM-USElab/gradecraft-development#2171]
Depends on #2080 and #2170

**Comment by jwright** [comment]
** Import

- [ ] `description` -> `description`
- [ ] `due_at` -> `due_at`
- [ ] `points_possible` -> `possible_points`
- [ ] `grading_type` -> `pass_fail` (only if grading_type is `pass_fail`

**Comment by jwright** [comment]
-  [ ] Only import visible assignments
