### ISSUE TITLE
Update Canvas assignments

### ISSUE THREAD

**Issue by ksofa2** [UM-USElab/gradecraft-development#2173]
As a professor
I should be able to update my Canvas Assignment that was imported from Canvas with GradeCraft data
So I can sync any changes with Canvas

**Comment by jwright** [comment]
@chcholman @mariehooper I feel like we need a section on the assignments show view (or somewhere) where the instructor can view the last time an imported assignment was imported vs. the last time it was updated locally. It may also hold a way to to turn on/off syncing? Thoughts?

**Comment by mariehooper** [comment]
@jwright- I agree! I can get a design for this ready early next week if that makes sense? Nothing crazy but just want to think about this in the same convo as the assignment redesign that @chcholman and I are thinking about.

**Comment by jwright** [comment]
@mariehooper Sounds great. Thank you!
