### ISSUE TITLE
Can't add first Grade Scheme Elements item

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#2217]
When you try to add the first item to the grade scheme elements, it fails the validations and won't add.

**Comment by chcholman** [comment]
- The first level added is assumed to be the ‘high point’, and both values need to be settable without validations against any other element (since they don’t exist)
- All additional levels should ‘respond’ to values in the adjacent levels, adjusting their high point in response to the above low point being altered, and reversed for low point and blow
- The level high and low point should be separated by at least 1 point, with the high value being higher than the low value
- Goal: we want to ensure that they add a level that starts with 0 and covers the full spectrum

**Comment by zazaian** [comment]
@chcholman is there a default value we want to use for the 'max' value on the first-added grade scheme element? Maybe 100, or 1000 just for demonstration's sake? Currently the min value is zero.

**Comment by chcholman** [comment]
@zazaian Actually let's remove the 0 as the min value default (the first element added is supposed to be the highest level, and so 0 would be confusing). I'm worried that entering any number in the max value field will prompt them to try to work around that as opposed to understanding that it can be changed.
