### ISSUE TITLE
Review Imported Grades from Canvas

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#2446]
As an instructor, I want to be able to click an "Import grades from Canvas" button that will pull in grades for a single assignment. Imported grades should be shown on a review page, where I can compare them to any grades already entered in GradeCraft for this assignment.

**Comment by chcholman** [comment]
@mariehooper Should have some wireframes/requirements about the data to be added for the review screen here

**Comment by mariehooper** [comment]
Hi @jwright ! Here are some visuals for the changes to the Canvas assignment import pages: 

## After clicking Import Grades (If Canvas integration is set up already):
![screen shot 2016-09-21 at 2 17 07 pm](https://cloud.githubusercontent.com/assets/12573921/18723334/1d802efc-8006-11e6-8446-13b694a37aeb.png)

## After choosing Canvas assignment to import:
![screen shot 2016-09-21 at 2 17 37 pm](https://cloud.githubusercontent.com/assets/12573921/18723347/2c90422e-8006-11e6-9d32-aa853ed27931.png)

**Comment by jwright** [comment]
@mariehooper A thought. In "after choosing Canvas" row #2, since the user has a gradecraft score, should we make it more noticeable that they will be overriding the grade that is there? Maybe an indicator next to the checkbox?

**Comment by mariehooper** [comment]
@jwright - Definitely. Maybe simple text that says 'Replace GC grade' in a column to the right of the checkbox that shows up if you check the box? (Not in love with that but I think it will work until we think of a better way) :)

**Comment by jwright** [comment]
👍
