### ISSUE TITLE
Canvas Course Linking

### ISSUE THREAD

**Issue by jwright** [UM-USElab/gradecraft-development#2453]
As an instructor
I should be able to link a Canvas course with a current GradeCraft Course
So that I do not have to select the course when importing assignments or grades

**Comment by jwright** [comment]
The workflow and details for this are specified in a comment on #2398

https://github.com/UM-USElab/gradecraft-development/pull/2398#issuecomment-248119823

**Comment by jwright** [comment]
@cait @mariehooper Does this replace any of the information in the course I am linking to in Canvas or does it simply link the GC course and the Canvas course together?

**Comment by chcholman** [comment]
@jwright Simply link.

**Comment by jwright** [comment]
👍

**Comment by jwright** [comment]
@chcholman @mariehooper What do you guys think about this view? This lives at `/integrations`. If the user clicks on "Link a Canvas Course", they will oauth and select a course from Canvas at which time they will be redirected back to `/integrations` with a different view since they already linked the course.

Thoughts? Check out the copy and icon too. I also thought about adding a "More coming soon" card.

![screen shot 2016-09-21 at 3 34 34 pm](https://cloud.githubusercontent.com/assets/35017/18726211/6ef64e00-8011-11e6-8b68-c612ad8a9ea3.png)

**Comment by chcholman** [comment]
@jwright Looks great to me!

**Comment by mariehooper** [comment]
@jwright I'm down! What does it look like when I am already connected with Canvas - thinking we need to show the Canvas course name thats linked and provide a way to unlink this course... keeping it in the card would be nice. @chcholman - thoughts?

**Comment by chcholman** [comment]
@mariehooper That sounds ideal.

**Comment by jwright** [comment]
@mariehooper @chcholman I was thinking the same thing :)
