### ISSUE TITLE
Unable to create/open lock file: /var/lib/mongodb/mongod.lock errno:13

### ISSUE THREAD

**Issue by igpg** [UM-USElab/gradecraft-development#2461]
While everthing was installed correctly without errors (remove Gemfile.lock  / install nodejs and libpq-dev as requirements before launching bundle install otherwise bundle install will fail).

And MongoDB is installed and running without problems : 
```
Fri Sep 23 11:12:17.165 [initandlisten] MongoDB starting : pid=7620 port=27017 dbpath=/var/lib/mongodb 64-bit host=ubuntu
Fri Sep 23 11:12:17.166 [initandlisten] db version v2.4.9
Fri Sep 23 11:12:17.166 [initandlisten] git version: nogitversion
Fri Sep 23 11:12:17.166 [initandlisten] build info: Linux orlo 3.2.0-58-generic #88-Ubuntu SMP Tue Dec 3 17:37:58 UTC 2013 x86_64 BOOST_LIB_VERSION=1_54
Fri Sep 23 11:12:17.166 [initandlisten] allocator: tcmalloc
Fri Sep 23 11:12:17.166 [initandlisten] options: { bind_ip: "127.0.0.1", config: "/etc/mongodb.conf", dbpath: "/var/lib/mongodb", journal: "true", logappend: "true", logpath: "/var/log/mongodb/mongodb.log" }
Fri Sep 23 11:12:17.533 [initandlisten] journal dir=/var/lib/mongodb/journal
Fri Sep 23 11:12:17.533 [initandlisten] recover : no journal files present, no recovery needed
Fri Sep 23 11:12:17.632 [websvr] admin web console waiting for connections on port 28017
Fri Sep 23 11:12:17.632 [initandlisten] waiting for connections on port 27017

```
foreman start fails to use mongodb : 
`11:15:07 mongo.1            | Fri Sep 23 11:15:07.603 [initandlisten] exception in initAndListen: 10309 Unable to create/open lock file: /var/lib/mongodb/mongod.lock errno:13 Permission denied Is a mongod instance already running?, terminating`

Which btw was the same point I was stuck on arch linux as well...

this are the permissions:
```
ls -acl /var/lib/mongodb/
total 81940
drwxr-xr-x  3 mongodb mongodb     4096 Sep 23 11:12 .
drwxr-xr-x 42 root    root        4096 Sep 23 10:14 ..
drwxr-xr-x  2 mongodb nogroup     4096 Sep 23 11:12 journal
-rw-------  1 mongodb nogroup 67108864 Sep 23 11:12 local.0
-rw-------  1 mongodb nogroup 16777216 Sep 23 11:12 local.ns
-rwxr-xr-x  1 mongodb nogroup        5 Sep 23 11:12 mongod.lock
```

What's the solution?
Thanks.

**Comment by igpg** [comment]
sudo chown -R yourusername /var/lib/mongodb/ fixes it but isn't that a bit risky running it as the localuser?

**Comment by chcholman** [comment]
Thanks so much for submitting this issue! 

Unfortunately we don't have the bandwidth the address installation issues at this time, but greatly appreciate the interest in using GradeCraft. I'm closing the two issues identifying challenges in the installation process on linxu/Ubuntu for now, but if our team grows in the future in such a way that we can make improvements to this process we will absolutely do that.
