### ISSUE TITLE
Remove empty grades

### ISSUE THREAD

**Issue by jwright** [UM-USElab/gradecraft-development#2488]
Create rake tasks to perform the following:
1. Delete any grade that has a `predicted_score` > 0
2. Delete any grade with a nil `raw_points` and a nil `feedback`
3. Populate the remaining grades with a nil `graded_by_id` with Cait's user id (1) (Do not update the `updated_at` field)
4. Populate the remaining grades with a nil `graded_at` with the grade's `updated_at` field (Do not update the `updated_at` field)
5. Create a migration to remove the `Grade#predicted_score` column

**Comment by jwright** [comment]
Depends on #2487

**Comment by jwright** [comment]
Blocked due to changes waiting in #1492

**Comment by chcholman** [comment]
No longer blocked!
