### ISSUE TITLE
Create a view to handle when a user has no course

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#2567]

**Comment by jonathoy** [comment]
<img width="1288" alt="screen shot 2016-12-20 at 9 16 07 am" src="https://cloud.githubusercontent.com/assets/17604722/21353655/021264de-c695-11e6-85b7-d2ea157c74dd.png">

@chcholman We had briefly discussed how to best word this message. Let me know if you come up with some ideas.

**Comment by chcholman** [comment]
@jonathoy Apologies for the delayed reply. Let's do: 

"You don't belong to any courses in GradeCraft! 

If you're a student, ask your instructor to add you to their course site. 

If you're an instructor, email help@gradecraft.com to have them create a course shell for you. 

Log me out..."
