### ISSUE TITLE
JSON::ParserError

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#2633]
### Actual Behavior
When importing an assignment, the import hits a JSON error as documented here: https://rollbar.com/gradecraft/gradecraft-development/items/1644/?item_page=0&#traceback

### Steps to reproduce
I know that an instructor and their TA both hit this repeatedly around the same assignment, I don't fully know what steps they took to create it. Will update if/when I can find out more.

**Comment by jwright** [comment]
@chcholman We can handle this elegantly but the real issue with Canvas. Do we have a Canvas contact that could tell us why this is failing?

**Comment by chcholman** [comment]
@jwright I will reach out to our UM Canvas team and let you know what I hear!
