### ISSUE TITLE
Refactor Students page

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#2704]
### Expected Behavior
The students page is one of the central places in the app, and needs to load in < 1 second. 

### Actual Behavior
With 300 students in a class on staging, it takes > 1 minute to load the page. 

### Steps to reproduce
Navigate to staging.gradecraft.com/students

**Comment by chcholman** [comment]
Former version of the `students_being_graded` query: 

https://github.com/UM-USElab/gradecraft-development/blob/d495408f58e670da05e0f039ccd94b08361b15c3/app/models/user.rb#L32

**Comment by jwright** [comment]
@chcholman Who should I sign in as on staging to see this query time?
