### ISSUE TITLE
Standardize the width of Rubric Review criteria name and feedback boxes

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#2780]
The grade review page is super useful, but I think it will be easier to make sense of visually if we can keep the criteria name and feedback boxes consistent widths to themselves. 

![screen shot 2016-12-28 at 9 55 53 pm](https://cloud.githubusercontent.com/assets/234276/21535809/7e5f402a-cd48-11e6-8272-263854f468bf.png)

**Comment by mariehooper** [comment]
@chcholman  - where is this?

**Comment by chcholman** [comment]
Example URL: http://localhost:5000/assignments/71/grades_review

**Comment by mariehooper** [comment]
@chcholman - thank you! I didn't know this existed :)
