### ISSUE TITLE
Enforce a text limit for description boxes and other manual entry areas

### ISSUE THREAD

**Issue by mariehooper** [UM-USElab/gradecraft-development#2803]
### Expected Behavior
Maximum character or word count enforced on text entry fields

### Actual Behavior
Text fields site wide are limitless

### Steps to reproduce
[Trello Card](https://trello.com/c/ampHw9BS/74-enforce-a-text-limit-for-description-boxes-and-other-manual-entry-areas)

**Comment by chcholman** [comment]
@mariehooper Do you have any thoughts about what the upper limit here should be?

**Comment by mariehooper** [comment]
@chcholman - I don't have a limit in mind... Maybe limit of 100million? I can't imagine we would advise anyone to use a scale of a billion points!

**Comment by chcholman** [comment]
Wait - for a text field limit? We've added numeric field limits (at 9)

**Comment by mariehooper** [comment]
@chcholman - whoops, I was thinking number. Text is hard because it probably shouldn't be a blanket total everywhere? Some fields are long response...  Maybe if its a textbox limit at something like 100 char but if textarea then much longer?
