### ISSUE TITLE
Allow for multiple Canvas institutions to be connected to GradeCraft

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#3001]
### Expected Behavior
As an instructor from a non-UM institution, I want to be able to import Canvas assignments and grades into my course

### Actual Behavior
I can currently only be routed to the UM Canvas domain.

**Comment by jonathoy** [comment]
@chcholman Correct me if I'm wrong but would this not require us to acquire and store OAuth keys and secrets for each of the other institutions that we plan to support?

If so do you have any thoughts as to how we might get ahold of someone at Dearborn, for instance, to obtain access?
