### ISSUE TITLE
Assignment average score seems slightly off

### ISSUE THREAD

**Issue by mariehooper** [UM-USElab/gradecraft-development#3058]
Class analytics - 'assignment average'

**Comment by chcholman** [comment]
So, the middle line of a boxplot is the median, not the mean/average. Is it possible that that's what we're seeing, or do you think there's another error in the mix?

**Comment by mariehooper** [comment]
@chcholman - you are exactly correct. Yesterday was a long day haha. I completely forgot that was median not mean.
