### ISSUE TITLE
Update grading form submission process

### ISSUE THREAD

**Issue by mariehooper** [UM-USElab/gradecraft-development#3095]
We need to implement the final portion of the changes to the grading form which will help instructors understand when students will see grades. This will need to happen in phases as 'Release necessary' will be removed as an option on assignment edit form and Grade Status select menu will be replaced with yes/no switch to release grade to student.

![grading-form-buttons](https://cloud.githubusercontent.com/assets/12573921/23824892/70ea037e-064d-11e7-872e-a5257d5875c0.png)

[Trello Card](https://trello.com/c/rkxNlEsW/65-change-the-can-the-student-see-this-grade-descriptor-next-to-the-grading-status-dropdown-so-its-meaning-is-clear)

**Comment by chcholman** [comment]
To complete this work, we need a slight revision to the button states when the grade is not visible to students. This work needs to handle two things: visible, and complete. 
- [ ] Add a boolean "complete" that is updated by a new (and first) switch, default in the form to true
- [ ] Add a boolean "visible" that is updated by the switch above, default to false 
- [ ] Button for the state of complete: false is "Save Draft" and "Save Draft and Grade Next"
- [ ] Buttons for the state of complete: true or all types is "Submit" and "Submit and Grade Next"
