### ISSUE TITLE
Options are disabled on Student Page after sort

### ISSUE THREAD

**Issue by dovek** [UM-USElab/gradecraft-development#3100]
### Expected Behavior
Options drop down menu should be available after sorting users on students page by last name

### Actual Behavior
Clicking the cog does not have any result after sorting students by last name on students page

### Steps to reproduce
Logged in as Dumbledore. Navigated to students page. Sorted by last name. Click on options cog. Nothing happens.

**Comment by mariehooper** [comment]
@dovek @chcholman - Pretty sure this is a dynatable issue (need to validate this). None of the js on the page loads after using dynatable sorting sometimes. We see it reoccur here and there.
