### ISSUE TITLE
Analytics page table sorting alpha rather than date

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#3247]
On the Analytics page, if you sort by last login it is sorting alphabetically, not by date (so April and August are first).

**Comment by inselbuch** [comment]
any table in Grafana with a column set to display as "Date" will not sort by date

**Comment by chcholman** [comment]
Thanks @inselbuch! We're using Dynatable, not Grafana, and are able to get things to sort by date, we just need to apply it to this particular column.
