### ISSUE TITLE
Respond_to not_authenticated filters

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#3417]
Now that we are building out more and more controllers and methods in the API namespace, it would be of benefit to make some changes to `application_controller` specifically in the `not_authenticated` method.

We protected many of our JSON routes with filters such as `ensure_staff?`, but the current functionality is that if the user is not authorized they will be redirected. This has the potential to cause two unwanted side-effects:

1. The request may return a status of 302 (Redirect)
2. Or if the request is being made by Angular's $httpProvider, per the official [docs](https://docs.angularjs.org/api/ng/service/$http):

> Note that if the response is a redirect, XMLHttpRequest will transparently follow it, meaning that the outcome (success or error) will be determined by the final response status code.

I propose that we `respond_to` the request type so that we continue to redirect if the request type is HTML. However, if the request type is JSON we should return a 401 Unauthorized status.

**Comment by maskib** [comment]
@ebarroso7 @chcholman Erik & Cait to assess whether this is a security concern
