### ISSUE TITLE
[Spring Cleanup] Remove duplicate Unlock States

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#3440]
This is data that now needs to be cleaned up - there should only be ONE unlock state per student per learning objective. We need to 

* [ ] Delete the unnecessary data in the database
* [ ] Constrain this on the database layer

**Comment by maskib** [comment]
Steps required to do this: 1. take a backup of the db 2. a day of erik, cait, james going through and do the deleting
