### ISSUE TITLE
Quick Access to draft submissions on the student dashboard

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#3454]
As a student, if I have a draft submission, I want to easily be able to access it/them on my dashboard

**Comment by mariehooper** [comment]
[Trello Card Design Reference](https://trello.com/c/c95eZH5W/100-add-in-progress-assignment-module-to-student-dashboard)

**Comment by chcholman** [comment]
➤ Erik Barroso commented:

@caitlinholman1 / @evanstr  Just saw this in trello. I could add this as a table in the same way I have been working on ungraded submissions and graded assignments table. we still would like this feature, right? 
Won't take me long at all to add

**Comment by chcholman** [comment]
➤ Caitlin Holman commented:

That would be awesome @erikbarroso2 !

**Comment by ebarroso7** [comment]
This was done in PR #4207
