### ISSUE TITLE
Increase accessibility of GradeCraft email links

### ISSUE THREAD

**Issue by mariehooper** [UM-USElab/gradecraft-development#3458]
Most GC emails use a "here" hyperlink instead of a more descriptive term. Some examples are assignment submission and grade release.

The email received for being awarded a badge uses a "click here" link that could be made more accessible by hyperlinking something like "other badges you can earn. 

Note: If there is no icon uploaded for the badge, even though the default icon displays on GC, the thumbnail is broken when included in an awarded badge notification email.

[Trello Card](https://trello.com/c/9cQQASKu/81-increase-accessibility-and-descriptiveness-of-gc-notification-email-links)

**Comment by chcholman** [comment]
@mariehooper We need to do a thorough overview of all emails and their text - let's make sure we do these at the same time!

**Comment by chcholman** [comment]
HTML Emails also display as code in Outlook Mobile
