### ISSUE TITLE
Add empty states to pages lacking data

### ISSUE THREAD

**Issue by mariehooper** [UM-USElab/gradecraft-development#3512]
### Expected Behavior
As an instructor, I expect to see a message with a clear call to action on pages that are blank due to a lack of data.

### Actual Behavior
Simply table headers show on pages when no data exists in table rows rather than a message presenting an actionable step for using this page.

### List of Pages
- [ ] announcements
- [ ] gradebook
- [ ] groups

**Comment by chcholman** [comment]
➤ Caitlin Holman commented:

For reference: https://docs.google.com/document/d/1rC9aGRNrlm8BHY2DXHB4qMGH6QowVDqEMm-VpmTAX3o/edit?ts=596fa049
