### ISSUE TITLE
Should be intuitive and explained that you can't create a rubric AND score levels

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#3676]
Upon talking to Evan, it might be of benefit to reorganize the assignment edit page a bit to make it so that rubrics can also be set up from the edit page. We may also want to allow one or the other to make it less confusing.

┆Attachments: <a href="https://trello-attachments.s3.amazonaws.com/5a6f2020d4ad818ef1fffe12/5a6f62e57fc25aa7ab8edb09/6dd9c2d5a8bc0e61e937de048506a2cf/Screen_Shot_2019-03-11_at_1.30.51_PM.png">Screen Shot 2019-03-11 at 1.30.51 PM.png</a>

**Comment by jonathoy** [comment]
Consult with Evan, as she may have additional thoughts on UX.

**Comment by chcholman** [comment]
You *can* create a rubric, but if you do, the display page with grades will check for score level outcomes and error when it can't find them

**Comment by chcholman** [comment]
➤ Erik Barroso commented:

@davidanesbitt Could you check if this is still around / happening ? 
I'm working in this same area in the code and could do a quick fix if its still acting funky

**Comment by chcholman** [comment]
➤ David Nesbitt commented:

I was able to create an assignment that had score levels and then add a rubric.

I was then able to submit an assignment for it as a student. I'm not sure if I could see the score levels when i was viewing the assignment as the student.

I was not able to see the score levels when grading the assignment.

**Comment by chcholman** [comment]
➤ David Nesbitt commented:

Another thing I noticed is that if you create an assignment and don't check the "Use rubric?" box, then if you go to the Grading tab you can't add a rubric' the rubric settings are not visible.

You have to leave the assignment edit page (by navigating back to Assignments or another page, or by clicking Update Assignment button), then come back to it and go to the Grading page, and then the Rubric feature will be visible again.

**Comment by maskib** [comment]
Part of the assignment redesign
