### ISSUE TITLE
Improve PaperTrail History for Submissions

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#3678]
The Papertrail-based history that's shown for submissions can be a bit confusing to the end user.

If a student begins typing text content and it autosaves, the history will show that they have created a submission even though it has not yet been submitted. Once they submit, the following change will show that they have updated the submission.

It might be of benefit to make it more apparent on the timeline that a submission's state has changed, whether that means it has been submitted or resubmitted.

**Comment by maskib** [comment]
Needs to be ripped out, but needs to be prioritized as a major feature upgrade when we have the bandwidth
