### ISSUE TITLE
Missing content on Gradecraft.com

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#3688]
Gradecraft.com is a little wonky in some places. If you go to the [Features](https://gradecraft.com/features.html) page for instance, there's some missing content and some 404 errors in the console.

I wasn't able to click the buttons to toggle Features for Instructors vs. Students.

Also if you hit any arbitrary link on gradecraft.com, instead of getting the custom 404 page you get an ugly 404 with some request details.

![screen shot 2017-10-05 at 10 13 05 am](https://user-images.githubusercontent.com/17604722/31231828-f8f141b8-a9b5-11e7-98a5-b620ed6ca55e.png)

**Comment by jonathoy** [comment]
Possibly related to #3680

**Comment by chcholman** [comment]
➤ Caitlin Holman commented:

@jonathonyu @sophiazhou10 Are we comfortable closing this ticket?

**Comment by chcholman** [comment]
➤ Sophia Zhou commented:

@caitlinholman1 @jonathonyu I think this should be resolved since we completely redid the public-facing pages, and as far as we can tell, all the links are taking you where you should go, right?

**Comment by chcholman** [comment]
➤ Caitlin Holman commented:

@sophiazhou10 @jonathonyu Yup! K, closing :)
