### ISSUE TITLE
Earned badge notifications being sent on autosave

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#3788]
If an assignment has been graded previously and an instructor goes back to edit, any time that they award a badge they will receive a notification. This should only happen after the changes have been submitted and not when the change is autosaved.

**Comment by chcholman** [comment]
➤ Michael Skib commented:

caitlinholman1 Good news - I have been unable to reproduce this issue! I wasn't sure if the "edit" Jon was referring to was to the grade or the assignment, so I tried both, and neither produced a notification on autosave. Shall we call this resolved? Happy to provide more info about what I tested, if you want to think through this more.

**Comment by chcholman** [comment]
➤ Caitlin Holman commented:

michaelskib Thanks so much for testing this! I'm going to close for now assuming we'd have heard from users if this was still happening broadly.
