### ISSUE TITLE
Learning Objective Table Showing Erroneous Info

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#3928]
As an instructor, the learning objective index page accessed via the navbar shows a table header for Count to Achieve, even though the course has been set up to use points.

See talent gateway in staging for details.

**Comment by chcholman** [comment]
This has been resolved! 
<img width="914" alt="screen shot 2018-07-30 at 9 09 26 am" src="https://user-images.githubusercontent.com/234276/43399219-4ca3d7b4-93d8-11e8-89b4-328b43cfa2d6.png">
