### ISSUE TITLE
Block LOs from being deleted if they've been assessed

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#3938]
There's a possibility where learning objectives and levels are set up and one or more students are assessed.

If the instructor goes back and deletes a learning objective level after grading, we are now left with a "hanging" outcome with a broken reference.

Most notably, this will result in a template error for the following endpoints that are used to obtain LO outcomes:

`API::LearningObjectives::OutcomesController#index`
`API::LearningObjectives::OutcomesController#outcomes_for_objective`

If this occurs, it's possible that this person may not see any outcomes for any objective.

A question we may want to ask is - should outcomes be destroyed if the level is deleted?

**Comment by jonathoy** [comment]
Pasting over from previous issue:

>Observed in staging as Camille Rice, assignment 4912.
>
>From the assignment show page, if you click on the Compentencies tab you won't see a selected outcome on the corresponding objective even though it has been assessed.
>
>Verified that the grade is Complete and Student Visible.

**Comment by chcholman** [comment]
To do item: Confirm in current state that instructors can't delete learning objective components UNLESS there are no related objects.

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4331
