### ISSUE TITLE
Badge Icons Not Being Properly Copied During Course Copy

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#3952]
Narrowed down issue to an obscure [bug](https://github.com/carrierwaveuploader/carrierwave/pull/1544#ref-issue-311745163) with Carrierwave:

Requires us to update Carrierwave to ~> 1.0

**Comment by jonathoy** [comment]
After taking an initial look at what it would take to update Carrierwave, it appears that it may not be as straightforward as we might like.

We rely on `carrierwave_backgrounder`, which has not had any new commit activity since Feb 2017. Unfortunately until the library is updated for compatibility with Carrierwave 1.0+, our only option may be to get rid of backgrounder entirely.

**Comment by jonathoy** [comment]
Based on some feedback, it seems that there may be some sporadic issues where badge icons become badge file attachments on the original course. Need to take a deeper look at this when coming back to this.

**Comment by chcholman** [comment]
➤ Erik Barroso commented:

should be fixed when we delete s3 / merge in carrierwave-settings2

**Comment by maskib** [comment]
@ebarroso7 Looks like this is fixed currently! How would you feel about me closing this issue, any objections?
