### ISSUE TITLE
Add some sort of indication that a badge is locked for a student on mass award page

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#3963]
Could be a locked icon or some sort of disabled input?

**Comment by maskib** [comment]
This appears to have been added, e.g. https://staging.gradecraft.com/badges/1688/earned_badges/mass_edit

![Screen Shot 2020-03-11 at 9 36 50 AM](https://user-images.githubusercontent.com/38505166/76422613-e1e17d80-637b-11ea-8e82-ea0c9dfc5d02.png)
