### ISSUE TITLE
Issue with ordering list of courses by total points or # of students

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#3974]
### Expected Behavior

In "manage courses", sorting the list of courses by total points or # of students would list them largest to smallest, in whichever order is selected. 

### Actual Behavior

It appears that those two columns are sorted "alphabetically" (versus numerically) - meaning, 99 would come after 975, which would come after 950,000. 

### Steps to reproduce
As instructor, click "manage courses" and click on the column heading to sort from largest to smallest. For example: 
<img width="908" alt="screen shot 2018-05-01 at 4 41 59 pm" src="https://user-images.githubusercontent.com/38505166/39493010-5ccee10c-4d5f-11e8-96e8-128d2616b115.png">

**Comment by jonathoy** [comment]
I'm having trouble replicating this, so it may have been fixed. Will reopen if necessary
