### ISSUE TITLE
Case sensitive email addresses

### ISSUE THREAD

**Issue by evanstraub** [UM-USElab/gradecraft-development#3976]
### Expected Behavior
The case of a user's email address in a GC record should not affect the ability of a user to log in.

### Actual Behavior
If the email address of a user includes upper case letters, users would be prevented from logging in, even if the user types in their email address in a matching case-sensitive form.

### Steps to reproduce
Change user's email to mixed case on the GC record side (Evan_Straub@WARMmail.com).  Try to log in with that mixed case email address or all lower case.

**Comment by jonathoy** [comment]
Relates to #3422.

In the last PR, the only change that was made was to downcase the user input prior to performing the user lookup. The issue with this is that it is still possible elsewhere in the app to save or create a user with an email that contains uNuSUal cAsIng, therefore the compare will fail.

Two possible solutions - do a true case-insensitive lookup on the user or add some sort of model callback that downcases all emails in the database.

**Comment by jonathoy** [comment]
Closed via #4087
