### ISSUE TITLE
Issue regarding Courses New_External path

### ISSUE THREAD

**Issue by dovek** [UM-USElab/gradecraft-development#3994]
courses/new_external throws error if you are staff! Should this be accessible at all?

If you are logged in as staff, and you attempt to go to the courses/new_external page, you will get an error. Furthermore, courses/new_external is open to the public. Should it be open to the public as well as those who already have accounts?

**Comment by maskib** [comment]
Since our account creation flow has changed and I'm not able to find a way to access the courses/new_external page, I'm going to close this issue. But please feel free to reopen if that seems incorrect!
