### ISSUE TITLE
Turn Linked Assignments on the Learning Objective Overview page for students into a table

### ISSUE THREAD

**Issue by evanstraub** [UM-USElab/gradecraft-development#4015]
(all sortable)
Linked Assignment Name
Submitted (Y/N)
Assessment (Proficient/Not Proficient)
Resubmit (Y/N)

**Comment by evanstraub** [comment]
For students - I think we were talking about students knowing that they *can* resubmit.  Since we are talking about competency, letting students know that this particular assignment is resubmitted would be important.

(My understanding is that from our perspective, a resubmit is just another submission, so it's not really trackable anyway.  And if we were tracking resubmissions, I'd say we tracked the number of times a resubmit occurred, not whether or not it was a resubmit).

**Comment by chcholman** [comment]
Great, thank you!
