### ISSUE TITLE
Student Learning Objective show page should show progress overview

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#4025]
"display X (number proficient) out of Y (total number needed)"

On each learning objective show page, also show this value, and make sure it's visible near to the top

Also: 

- [x] Top align this table
- [x] Add locked/key indicators to assignments 
- [x] Add visibility controls from the assignment index page 
- [x] Order assignments by assignment type, and then by instructor ordered position
- [x] If assignments have been submitted, add the date in the Submitted? column
- [x] If an assignment can be resubmitted, add that in the "Resubmit?" column

**Comment by jonathoy** [comment]
Individual LO show page needs the context icons - submitted assignment, lock/unlocks, etc

**Comment by jonathoy** [comment]
Currently no icon to imply a resubmission either on assignment index or LO show
