### ISSUE TITLE
Decide what should show in the Grade/Submission history for each role

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#4035]
We should do a thorough review of the things that PaperTrail logs. For instance on a grade, a student can see this:

![screen shot 2018-07-31 at 10 53 05 am](https://user-images.githubusercontent.com/17604722/43467571-f54234d8-94af-11e8-96ad-ba2903d8df32.png)

Things like changing the grade's completion and visibility state don't really make sense to the end user.

As a general note, there are three models that currently are tracked via PaperTrail:

- Submission
- Submission History
- Grade

**Comment by maskib** [comment]
To be prioritized as a major feature upgrade when we have the bandwidth
