### ISSUE TITLE
Attendance Descriptions don't show in Attendance view

### ISSUE THREAD

**Issue by evanstraub** [UM-USElab/gradecraft-development#4065]
### Actual Behavior
Description is only visible in Assignment view (the Description field appears blank in Attendance view)

### Steps to reproduce

**Comment by chcholman** [comment]
➤ Caitlin Holman commented:

michaelskib I checked into this this morning, but can't seem to reproduce - can you confirm?

**Comment by chcholman** [comment]
➤ Michael Skib commented:

caitlinholman1 I can't either, shall we archive this card?

**Comment by chcholman** [comment]
➤ Caitlin Holman commented:

michaelskib Yes please!
