### ISSUE TITLE
Grade Predictor Preview Issue (Instructor Side) - Low Priority

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4074]
### Expected Behavior
The Instructor grade predictor preview would function the same way that a student's would

### Actual Behavior
Currently, when multipliers are enabled in a course, the instructor's grade predictor preview will not work, because there's not a way to apply the multipliers to specific grade categories.

![screen shot 2018-08-27 at 2 16 09 pm](https://user-images.githubusercontent.com/38505166/44677398-cfa32700-aa03-11e8-87e3-9ad881f1bbd5.png)

### Steps to reproduce
1. Choose any course with multipliers enabled, e.g. - https://staging.gradecraft.com/courses/938/edit
1. Navigate to the grade predictor preview for that course.
1. Scroll through the course and you'll notice that there's not a place in the UI to apply multipliers to each grade category. The total earned, total predicted, and predicted final outcome will also be blank, not even displaying a zero.
1. Enroll yourself as a student in the course, and log into an incognito course as that student.
1. Go to the student's grade predictor page. You should be able to see the unused multipliers and apply them by clicking in the designated circles to the right of the total points value for a category.

**Comment by chcholman** [comment]
@maskib Will you investigate this further? There are courses where the instructor grade predictor preview works (for instance Talent Gateway's shell) but many others where they don't. One note so far - the multipliers/weighting feature is definitely appearing in the interface even when it's turned of - that might have something to do with it. Any further identification of what features appear to be on when the Instructor GPP fails would be huge for figuring this out. I've confirmed that we are not observing errors in Rollbar or the console when these happen.

**Comment by maskib** [comment]
@chcholman No problem, happy to! One thing I've noticed with my staging test course is that the multipliers/weighting feature appears on even when it's off if it has been turned on in the past - it's like it doesn't realize it's been turned off. 

Do you have any example courses where the preview isn't working, or will these be easy enough to find?

**Comment by chcholman** [comment]
@maskib Yours is one of them. Talent Gateway is working. Boiling water was not.

**Comment by maskib** [comment]
@chcholman (see description above) Is this better? Let me know if I can provide more info!

**Comment by chcholman** [comment]
@maskib - so that's true (and a legit bug) but I was hitting this (or some variant of it) even in courses where multipliers are off...

**Comment by maskib** [comment]
I'll keep looking then!

What you describe could be my test course, where multipliers are turned off, but had been turned on in the past. It seems like the grade predictor never realizes that multipliers got turned back off, if that makes sense. @chcholman

**Comment by chcholman** [comment]
@maskib Oh interesting, that could make a lot of sense. So, previous multiplier values not getting 'cancelled' essentially. I think with that we'd be good to explore from a dev side!

**Comment by maskib** [comment]
Exactly. Great! Want me to write that up as a separate bug or do you think that's good?

**Comment by chcholman** [comment]
Nope, this is perfect, thank you!

**Comment by chcholman** [comment]
➤ Michael Skib commented:

caitlinholman1 Alright if I move this card to a different category? Bugs perhaps?

**Comment by chcholman** [comment]
➤ Caitlin Holman commented:

michaelskib Done!

**Comment by maskib** [comment]
Recreating a way for instructors to manually set multipliers would be easier (e.g. text boxes), but still low impact
