### ISSUE TITLE
Misc UX 

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#4088]
- [x] The buttons on the criterion levels for a rubric have overflowing text

![screen shot 2018-09-06 at 8 48 26 am](https://user-images.githubusercontent.com/17604722/45166010-ff9cb800-b1c3-11e8-8bdb-47ce37ecf719.png)

- [x] The draggable icon in the top left corner when reordering criteria on a rubric blends in with the yellow background and is barely visible. For reference, it is the black icon that you see in the image below

![screen shot 2018-09-06 at 8 46 49 am](https://user-images.githubusercontent.com/17604722/45166054-235ffe00-b1c4-11e8-982a-b2594c018762.png)

- [x] The learning objective levels disappear at a screen width =< 640px, when grading a specific student

![screen shot 2018-09-06 at 11 03 10 am](https://user-images.githubusercontent.com/17604722/45166211-7afe6980-b1c4-11e8-9622-8660aece2131.png)

**Comment by jonathoy** [comment]
- [ ] Let's meet with @evanstraub to discuss the overall rubric UX since we just received some feedback from one of our users

**Comment by sophiazumich** [comment]
this relates to, and has caused, Issue #4090
