### ISSUE TITLE
Learning Objective Level shuffling

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4094]
### Expected Behavior
Once created and saved, you would expect the learning objective proficiency levels to stay in the same order that they were.

### Actual Behavior
Sometimes, the proficiency levels shuffle around. There is not an obvious consistent pattern to how this happens, and that is most clear when there are at least 4 different proficiency levels. It also happens most consistently with newly created learning objectives: if you immediately add the proficiency levels (without clicking "save changes" in between), this seems to be far more likely to happen.

### Steps to reproduce
See actual behavior above. Create a new LO, add 2 or more proficiency levels, click "save changes", then go back to edit the LO. Sometimes the levels will be shuffled. Sometimes they won't, though. It's very strange. I wonder if it's related to the autosaving?

**Comment by jonathoy** [comment]
#4095 adds in a couple missing places where we should have been displaying levels based on their sort ordering. We should talk about whether we want to allow users to sort manually, or if we want to maybe just sort for them based on the proficiency level.
