### ISSUE TITLE
Require that a learning objective have at least two levels

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#4114]
_Originally posted by @maskib in https://github.com/UM-USElab/gradecraft-development/pull/4108#issuecomment-426011639_

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4329

**Comment by chcholman** [comment]
➤ adishy commented:

Has not been built on staging yet due to OpenShift database migration

**Comment by chcholman** [comment]
➤ Erik Barroso commented:

https://github.com/UM-USElab/gradecraft-development/pull/4368
