### ISSUE TITLE
Inconsistent assignment visibility when assignment is locked

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4119]
### Expected Behavior
AS A STUDENT: When an assignment is set to be visible when locked, but the name is not set to be visible, the display of this assignment would be consistent between the "assignments" view, and the view of assignments that meet a certain learning objective. 

### Actual Behavior
AS A STUDENT: When an assignment is set to be visible when locked, but the name is not set to be visible, the behavior is as expected on the assignments page, but I can still see the name of the assignment on the page displaying assignments that meet a certain LO, and if I click the name of the assignment, I get a "server error".

### Steps to reproduce
As an instructor, Create a new assignment, set it to meet a certain LO. Set the visibility settings to assignment visible when locked, but make sure that the other visibility settings are unchecked. Then, as a student look at the LO page for the LO you assigned this assignment to, and you should see the name of the assignment in that list. Try clicking it and see if you get a server error!

**Comment by ebarroso7** [comment]
Hey @maskib , could you check to see if this is still an issue? Just tried to recreate the issue and it looks like it was fixed but I could be wrong

**Comment by maskib** [comment]
The check works as intended!
