### ISSUE TITLE
Assignment unlock conditions do not copy when copying an assignment

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4121]
### Expected Behavior

Assignment unlock conditions should copy when copying an assignment.

### Actual Behavior

Assignment unlock conditions do not copy when copying an assignment.

### Steps to reproduce
Create an assignment, set any unlock condition you want. Copy that assignment, and check to see if the unlock conditions are there in the copied assignment.

**Comment by chcholman** [comment]
➤ Erik Barroso commented:

@michaelskib  could you test this guy too? 
https://github.com/UM-USElab/gradecraft-development/pull/4214

**Comment by chcholman** [comment]
➤ Michael Skib commented:

Unlock conditions appear to be copying correctly now!
