### ISSUE TITLE
When faculty change unlock conditions after assignments have been graded, unlocks do not retro-unlock

### ISSUE THREAD

**Issue by evanstraub** [UM-USElab/gradecraft-development#4134]
### Expected Behavior
An instructor changes "unlock conditions" for a badge/assignment after an assignment has been graded.  It would be expected for the unlock to recognize the change and re-evaluate the unlock based on the new lock conditions

### Actual Behavior
The lock does not change, and the instructor has to manually unlock for that assignment/badge

### Steps to reproduce

**Comment by chcholman** [comment]
➤ Caitlin Holman commented:

The key design challenge here is: 1) what expectations should we set for instructors regarding what happens, and 2) how should we communicate it to them?

**Comment by maskib** [comment]
We could add an additional UI where, if the instructor edits an unlock, we have another screen that provides a list of students impacted by the change. And then the instructor chooses if they want to retroactively email/take an action.
