### ISSUE TITLE
Oval-shaped "close" icon on badge edit page

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4137]
### Expected Behavior
The "close" (X) icon should be the same shape as everywhere else.

### Actual Behavior

The icon on the badge page, after you upload an image, is oval-shaped and the X is off-center:
<img width="1552" alt="screen shot 2018-11-09 at 2 50 31 pm" src="https://user-images.githubusercontent.com/38505166/48284942-07c8dc00-e42f-11e8-920e-0e9526d52cf4.png">

### Steps to reproduce
Create a badge, and add an icon image for that badge. You'll see that the "X" button is a little bit funky!

**Comment by sophiazumich** [comment]
I believe this is now fixed. I verified on staging.gc by choosing to "Edit" some badges and the button was no longer jank but instead nicely rounded.

**Comment by sophiazumich** [comment]
![screen shot 2018-11-20 at 9 10 10 am](https://user-images.githubusercontent.com/40248497/48778781-1a9ba600-eca4-11e8-989b-72c0c118d45e.png)
