### ISSUE TITLE
Refresh styling on error pages

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#4144]
Now that we've updated the overall styling in Gradecraft, we should probably also update the error pages so that they are consistent with the current look and feel.

One page is http://localhost:5000/errors?error_type=without_course_membership&status_code=401, which is normally shown when a user is logged in and without access to any courses.

The other page is the generic 404/500 page.

To view this page locally, one way is to look in `development.rb` and change the following configuration value to false:

```
# Show full error reports.
config.consider_all_requests_local = true
```

At this point, you can visit any link that doesn't exist and you will get the error (e.g. http://localhost:5000/party_parrot)

**Comment by maskib** [comment]
This has been resolved!
