### ISSUE TITLE
Possible Visibility/View Discrepancy With LOs

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#4147]
See Laurie's notes from last TG meeting. - 

Discrepancy in Learning Objectives count, eg.
Leadership Competency - Challenge # 4 - 5962
Participate in an Intramural club 4922 (ghost assignment - he did not submit, but it’s showing on the student preview screen as if he did)
But Challenge #4 is a hidden challenge, but the student submitted the assignment and in theory should see it?  But when it was un-hidden it shows up - so there’s a view thing on hidden
Priyal Sheth - 5956

https://umich.gradecraft.com/courses/110/edit

**Comment by chcholman** [comment]
➤ Michael Skib commented:

caitlinholman1 I'm not positive but it seems like this has been resolved. I'm not seeing the discrepancy Laurie originally described to us.

**Comment by chcholman** [comment]
➤ Caitlin Holman commented:

Awesome, thanks so much michaelskib !
