### ISSUE TITLE
Instructor Assignment Analytics display previous assignment predictions, not upcoming assignment predictions

### ISSUE THREAD

**Issue by evanstraub** [UM-USElab/gradecraft-development#4157]
### Expected Behavior
When an instructor goes to Analytics - Assignment analytics, instructors should be able to see both previous and upcoming assignments, including how many students predicted to complete assignments.

### Actual Behavior
Currently looking at Assignment Analytics displays only previous assignments (by date) and how many students predicted to complete the assignment.

### Steps to reproduce

**Comment by maskib** [comment]
Testing this on 3/11/20, this appears to be resolved.
