### ISSUE TITLE
Build Document Size Validation into Analytics::Event

### ISSUE THREAD

**Issue by jonathoy** [UM-USElab/gradecraft-development#4167]
Currently we check if an underlying event document has exceeded the maximum allowable size imposed by MongoDB prior to enqueueing the Resque job - see `app/event_loggers/pageview_event_logger.rb`

It might be better if we just add a custom validator class and hook to the underlying Rails model represented by Mongoid (`lib/analytics/event.rb`)

If it has exceeded the maximum size, we could probably continue to throw the `EventLogger::Exceptions::DocumentSizeExceededError` and have resque-retry ignore it.

This might help alleviate the following exception that we are seeing in Rollbar by cutting down on the overall number of MongoDB read transactions (without upping pool size in the config):

```ruby
Timeout::Error: Timed out attempting to dequeue connection after 1 sec.
```

**Comment by jonathoy** [comment]
This is contingent upon our usage of MongoDB as a data store for events

**Comment by maskib** [comment]
@chcholman Did we build this validation when we removed mongo?
