### ISSUE TITLE
Add date input for course analytics data

### ISSUE THREAD

**Issue by ebarroso7** [UM-USElab/gradecraft-development#4170]
### Expected Behavior
Right now submissions analytics is working for smaller courses, but when we try to run this for Talent Gateway, the amount of data is so large that it fails to send an email.

We have checked this through the rails console and found that everything runs successfully, the email just fails to be delivered, also not showing up in mandrill / mailchimp  as trying to deliver.

### Steps moving forward
Add ability to filter the analytics report to a specific date period. Under the submission analytics area, give two date input fields defaulted to a months time 

Futureland -- have submission analytics exporter use amazon S3

**Comment by jonathoy** [comment]
Another option that might be minimal effort to implement is for us to just compress the CSV prior to sending it. Then we can verify for sure if there is really an issue going on with the size of the output file. Looks like we can use a standard Ruby library to do this:

https://philna.sh/blog/2018/02/25/gzip-file-ruby/
