### ISSUE TITLE
Unlock visibility conflicts

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#4171]
### Expected Behavior
As an instructor, I expect that if an assignment is set to be invisible, then it will not appear in the list of unlock requirements/keys. 

### Actual Behavior
However, this setting is being overridden by the visibility controls established in the unlock conditions. So if an invisible assignment is set to show in the unlock conditions, it will show.

### Steps to reproduce
Create an assignment that is set to invisible. Make it a key for another assignment. Go look at the requirements for that assignment - the 'hidden' assignment will appear.

**Comment by maskib** [comment]
This is part of Sophia's assignment redesign. There should be a notification that says "this is an invisible assignment and will not show until its conditions are achieved"
