### ISSUE TITLE
Scrolling breaks when menu is expanded then browser window is widened [CHECK AGAIN AFTER VUE]

### ISSUE THREAD

**Issue by daviddangern** [UM-USElab/gradecraft-development#4180]
### Expected Behavior
When my browser window is horizontally condensed smaller than 1020 px wide, the left side nav menu appears as a hamburger button in the top left corner. If I open that menu and then widen my browser window beyond 1020 px so that the regular non-condensed menu comes back, I should still be able to scroll up and down on the page I'm viewing.

### Actual Behavior
When you open the condensed menu (window is less than 1020 px wide), then widen your browser window so that it's greater than 1020 px wide, the page won't scroll up or down. You can still click everything normally, but you can't scroll at all. If you refresh the page the scrolling functionality turns back to normal. If you condense your browser window again so that it's less than 1020 px wide and close the menu, then make the browser window wider than 1020 px wide again, the scrolling functionality will work fine.

When you have that condensed menu open, you can scroll up and down within it, but the page behind it is greyed out and scrolling is frozen, which makes sense. But it seems that this scroll lock is still being applied when you widen your screen again and make the menu disappear.

### Steps to reproduce
Go to Dashboard on either UMich or app site. Make your browser window less than 1020 px wide. Open the side nav menu using the hamburger button. Now while the menu is expanded, make your browser screen wider than 1020 px. The scrolling functionality will now be frozen.

**Comment by sophiazumich** [comment]
![screen shot 2019-02-15 at 9 53 26 am](https://user-images.githubusercontent.com/40248497/52864179-98d2e180-3107-11e9-9121-43a83ce3fa48.png)

**Comment by sophiazumich** [comment]
@daviddangern Part of the design refresh—and new brand/build guidelines—is to improve the UI regarding the nav. So @ebarroso7 and I hope to address this soon in a dev cycle. The main hope is to make the nav behavior and layout consistent for both instructors and students, allowing them to minimize or open the side-nav whenever they wish, and not removing any of the nav links whether you're mobile/small-screen or not—I think there's some funky logic that hides "irrelevant" nav items when you're on a smaller screen, but it's buggy and maybe isn't keep track of if you widen your screen again. 

Anyway! With this feature improvement coming in the future, and this being a lower priority bug, maybe we'll let it be for now until there's bandwidth to update the navigation UI entirely.
