### ISSUE TITLE
Menu items disappear at different browser window widths

### ISSUE THREAD

**Issue by daviddangern** [UM-USElab/gradecraft-development#4181]
### Expected Behavior
Menu items will stay the same, no matter what my browser window width is.

### Actual Behavior
**For Admin Accounts**
The items in the Course Setup and Admin sections of the app are the items that change. When the the browser window is at 1020 px wide or larger, the Course Setup section contains 5 items and the Admin section contains 7. When the window is smaller than 1020 px, the Course Setup section contains 5 sections and the Admin section contains 10 items. When the browser window is smaller than 640 pixels wide, the Admin section disappears and the Course Setup section contains 7 options (it looks like the Admin section gets absorbed into the Course Setup section).

The menu items that disappear completely at some browser window widths are My Account, View Tour, and Logout.

**For All Accounts**
The View Tour button only shows up when the browser window width is between 1020 pix and 640 px. When browser window width is outside of that range, the View Tour item does not appear in the menu. It also doesn't do anything when clicked, but I'll document that in a separate bug.

### Steps to reproduce
Go to UMich or app site. Change the width of your browser window, expand the side nav menu using the hamburger button when necessary, and watch the menu items change.

<img width="1537" alt="screen shot 2019-01-08 at 4 59 35 pm" src="https://user-images.githubusercontent.com/18683205/50998151-97a10a00-14f4-11e9-887e-0562b2a7a126.png">
<img width="1073" alt="screen shot 2019-01-08 at 4 59 49 pm" src="https://user-images.githubusercontent.com/18683205/50998152-97a10a00-14f4-11e9-97b1-c1c0ca7b423c.png">
<img width="743" alt="screen shot 2019-01-08 at 5 00 02 pm" src="https://user-images.githubusercontent.com/18683205/50998153-97a10a00-14f4-11e9-8dd3-575399a83b4e.png">

**Comment by sophiazumich** [comment]
@daviddangern I think I accidentally included my comment on this bug in Issue #4180 
I think the same comment applies here: in short, the design refresh and brand/build guidelines improves the current nav features, so it will be addressed in the (perhaps/hopefully-near) future.

**Comment by sophiazumich** [comment]
![screen shot 2019-02-15 at 9 53 26 am](https://user-images.githubusercontent.com/40248497/52864897-3ed31b80-3109-11e9-9f76-bb0af77c034c.png)
