### ISSUE TITLE
Submitting a group assignment triggers a server error

### ISSUE THREAD

**Issue by evanstraub** [UM-USElab/gradecraft-development#4183]
### Expected Behavior
When a student submits an assignment for a group that has a dependency, it should submit
### Actual Behavior
The student receives a server error
### Steps to reproduce
Create a group assignment as an instructor.  Have the assignment be either a key or locked.  Students create groups, Instructor approves the group.

Student goes into the assignment, clicks the "Submit" button.  They have the ability to type in text or attach a file, but when they click the "Submit" button to finalize their submission, they get a server error.  

Saving as a draft does not encounter the same thing, and if the group assignment does not have a dependency, it also will submit.

**Comment by ebarroso7** [comment]
Cherry-picked this commit d368b28b6eb5392cad613c53481a899d692f3d32 onto production and beta branches - so there was no PR to close this issue.
