### ISSUE TITLE
Attaching an image to badge prior to save deletes description text

### ISSUE THREAD

**Issue by evanstraub** [UM-USElab/gradecraft-development#4203]
### Expected Behavior
When creating a badge, a user should be able to write a description and continue to edit the creation form and retain description information while interacting with other pieces of the form

### Actual Behavior
The instructor can write a description for the badge and when he/she clicks the "Attach Icon" the description for the badge disappears.  This happens even after the description text has been marked as "autosaved."  This only occurs on the initial badge creation.  Editing an existing badge by taking out the text and changing the icon picture does not replicate the issue.

### Steps to reproduce

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4319
