### ISSUE TITLE
Enable Rubrics to be used in self logged assignments

### ISSUE THREAD

**Issue by ebarroso7** [UM-USElab/gradecraft-development#4208]
### Expected Behavior
Self graded assignments should be able to have rubrics that the students go through to give themselves grades.

### Actual Behavior
Because of prior complexities with rubrics and student graded assignments, rubric visibility has been disabled when an assignment is marked as student-logged. This is best observed from the changes made in this PR -- https://github.com/UM-USElab/gradecraft-development/pull/4205

Most changes in the referenced PR hide anything rubric related if the assignment is student-logged. However, it does block a rubric from being created in the first place if the assignment is marked as 'student-logged' before a rubric is created --> a test was added in the spec file for the find_or_create_rubric function. 

### Steps to reproduce
Create an assignment that is self logged and also has a rubric. Then when the student goes to complete the self grading, the rubric will be used to tally points - instead of automatically awarding full points. 

### Additional Features: 
[ ] - Allow students to delete their submission and grade before the due date of the assignment to allow for a clean resubmission 

[ ] - Improve workflow of students self logged assignments. Have the ability to start a submission (attachment, link, text, etc.), grade your work (using rubric, levels, or acknowledgment of completion) all from the same page.

**Comment by maskib** [comment]
@ebarroso7 https://github.com/UM-USElab/gradecraft-development/issues/4216

**Comment by maskib** [comment]
Part of the individual Assignment page redesign (Joy has helped to redesign this for the student-facing UI)
