### ISSUE TITLE
Make it possible to add an inline image in Froala

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#4210]

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4369

**Comment by maskib** [comment]
@adishy @ebarroso7 Currently, submissions exports from individual assignments and the assignment structure export don't seem to be working properly. They are supposed to be emailed, but aren't being emailed. The submissions export's status is stuck in "in progress"

![Screen Shot 2020-03-04 at 2 41 56 PM](https://user-images.githubusercontent.com/38505166/75916452-5b321b00-5e26-11ea-80ac-f635da499e7a.png)

**Comment by chcholman** [comment]
➤ adishy commented:

This should be working now. For the submissions export from individual assignments, it does take a couple of minutes if there are a lot of submissions. The assignment structure export should now also be mailed. Text submissions (with and without inline images) are now attached as pdfs in the submissions export. In the assignment structure export, if inline images are inserted in the assignment description/purpose, an archive of the images will be mailed with the exported CSV.

**Comment by maskib** [comment]
@adishy @ebarroso7 This is looking great!! No further questions, your honor :)
