### ISSUE TITLE
Rubric criteria and levels are duplicated when enabling/disabling student-logged mode

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4216]
### Expected Behavior
Rubric criterion and levels should remain unchanged when switching on and off the student-logged setting for an assignment.

### Actual Behavior
When editing an assignment, if a rubric has been created, the rubric criteria and levels appear duplicated when enabling and disabling student-logged mode. You have to look at the grading tab again BEFORE clicking "update assignment". Clicking update assignment seems to make the additional copies disappear. However, the copies can be edited, and those edits will actually be made to the original criterion or levels. This so far appears to be an admin facing issue only.

![52685240-0ec42680-2f17-11e9-90f9-2d2a1aa59c6a](https://user-images.githubusercontent.com/38505166/53764443-4f221f00-3e9b-11e9-920f-dda4a052c149.png)

### Steps to reproduce
1. Create an assignment and add a rubric
2. Check the "student-logged" box in assignment settings, and then uncheck it.
3. Look at the rubric again - you'll see that all criteria and levels appear duplicated. 
4. Make a change to one of the duplicated criteria or levels
5. Click "update assignment". 

At this point you should see that the changes have persisted even though the duplicate criteria and levels have disappeared. Just seems like this might be concerning to instructors using these features!

**Comment by chcholman** [comment]
➤ adishy commented:

Just a bug on the client-side (in angular/services/RubricServices.coffee > getRubric), each time the student logged button was toggled, duplicate elements were being pushed in.
