### ISSUE TITLE
Cannot delete an assignment category after a submission has existed in that category

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4227]
### Expected Behavior
Assignment categories shouldn't be able to be deleted when there are submissions or grades in that category. But I would expect that you would be able to delete an assignment category after deleting all of the grades and/or submissions in that category. After deleting all of the grades in a given assignment category (one that had no submissions) you can delete that category. However...

### Actual Behavior
If there are submissions in an assignment category, after deleting all submissions in that category, it's still not possible to delete the category itself. 
<img width="1551" alt="Screen Shot 2019-04-04 at 11 23 07 AM" src="https://user-images.githubusercontent.com/38505166/55567940-b1ee1c80-56cc-11e9-9a4e-0fe0d8d76f05.png">

### Steps to reproduce

1. Create a new assignment category
2. Create an assignment in that category that accepts submissions
3. Log in as a student and submit something to that assignment
4. As an admin, delete the student's submission
5. Attempt to delete the assignment category that had this submission. You should see that the delete button cannot be clicked, and the "information icon" with the hover tooltip is still present to the right of (what should be) the delete button.

**Comment by chcholman** [comment]
➤ Erik Barroso commented:

Actually delete the grade object  -- don't just switch the "student_visible" to false
