### ISSUE TITLE
CSRF Tokens with Vue.js

### ISSUE THREAD

**Issue by jlost** [UM-USElab/gradecraft-development#4233]
Rails auto generates CSRF tokens which are required in any non-GET API request. These will need to be integrated into our Vue.js code somehow. 

Here is how one person solved the problem: https://codeburst.io/form-validation-in-rails-with-vue-js-1910ec3c80c9

**Comment by ebarroso7** [comment]
Protected by ~ ` skip_before_action :verify_authenticity_token `

In app/controllers/api/licenses_controller.rb line 3

**Comment by ebarroso7** [comment]
closed by commit 56f5486d0bcf1634e
