### ISSUE TITLE
Video uploads in Froala editor not working

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4238]
### Expected Behavior

Clicking the "insert video" button in the froala editor toolbar allows you to upload a video. Video should still be visible and playable after reloading the page, clicking "update assignment" (if it's an assignment), etc.
## Actual Behavior

Some browser versions will allow video uploads. After reloading the page, or clicking "update assignment" (if you're editing an assignment description), the video player object exists within the text box, but appears blank, as though it's not finding any associated video content:
![Screen Shot 2019-04-19 at 10 09 59 AM](https://user-images.githubusercontent.com/38505166/56427910-8e5dd100-628b-11e9-91ad-642b9adce3fa.png)

Some browser versions (such as Chrome 73.0.3683.103 with Mac OSX 10.13) won't even let you upload a video in the first place. 

### Steps to reproduce

1. Go to any assignment, and click "edit"
2. In the "assignment description" field, click the "insert video" button.
3. Click the "drop video" upload zone. 
4. Upload a video file of your choice. Either this won't be possible, as video files will be greyed out and unselectable in the finder window, or this will be possible.
5. If you were able to upload a video, click "update assignment". You should see a blank video player, like the one in the screenshot above.

**Comment by maskib** [comment]
This issue has been resolved on staging, but not on app. @ebarroso7 @adishy is this related to the froala inline images pull request?

**Comment by ebarroso7** [comment]
@maskib  I'm not sure this was ever working on staging ? I just tested it on staging and it was broken for me. Also broken locally

**Comment by ebarroso7** [comment]
made a new branch if we would want to turn this off while it is broken 
https://github.com/UM-USElab/gradecraft-development/tree/turn-off-inline-video

**Comment by maskib** [comment]
@ebarroso7 Can you describe how it's broken for you? I was able to upload and play an inline video without any issues.

**Comment by ebarroso7** [comment]
So on both staging and prod i'm able to insert links to youtube and those play great, but when i go to upload a video from my machine it breaks. 

the branch i made would not allow you to insert links to youtube

**Comment by maskib** [comment]
@ebarroso7 I think the issue may be broader than linked videos, seems like uploaded videos have the same problem you're describing.

**Comment by maskib** [comment]
@chcholman @ebarroso7 Cait is planning on investigating whether we can disable video uploads only while still allowing video URLs, as a temporary fix.
