### ISSUE TITLE
On the Umich "https://umich.gradecraft.com/users/new" page there is a missing link

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4247]
In the screen shot below, you'll see that the page referenced has a notice about non-um users logging in. The link being provided on that page is for the same page you're currently on, and if a user that's not logged in tries to navigate to that link, they'll be taken to the umich homepage and still have to do the U of M authentication, contrary to what the note says
<img width="1552" alt="Screen Shot 2019-05-09 at 10 19 44 AM" src="https://user-images.githubusercontent.com/38505166/57462305-9daabb80-7246-11e9-9530-bf1bf948327b.png">

https://umich.gradecraft.com/users/new

**Comment by ebarroso7** [comment]
Hi Michael, I think this is a little bit more than a broken/missing link. 

I'm not too sure what functionality we are going for with this link but I don't know where we would direct a new user to create an account and add themselves to a course?  Thats what I understand the goal to be from the wording of the note.

**Comment by ebarroso7** [comment]
umich.gradecraft.com/login 

also should be hidden to users who are on app

**Comment by chcholman** [comment]
➤ Michael Skib commented:

caitlinholman1 Should this also be hidden on staging, or visible on staging?
