### ISSUE TITLE
In account notifications, make it possible to see which notifications you've read and which notifications you haven't. [CHECK AGAIN AFTER VUE]

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#4248]
Left border for each announcement on the “all announcements” page renders briefly and then disappears into the mists of time. (See screenshots)

┆Attachments: <a href="https://trello-attachments.s3.amazonaws.com/5a6f2020d4ad818ef1fffe12/5cd9b93cf954d5176f310784/f8decf8e7b09dc1a6b7924bffc3f9366/Screen_Shot_2019-05-13_at_2.37.44_PM.png">Screen Shot 2019-05-13 at 2.37.44 PM.png</a> | <a href="https://trello-attachments.s3.amazonaws.com/5a6f2020d4ad818ef1fffe12/5cd9b93cf954d5176f310784/eeec957b10817564b558a367a38cbd8d/Screen_Shot_2019-05-13_at_2.39.06_PM.png">Screen Shot 2019-05-13 at 2.39.06 PM.png</a>

**Comment by maskib** [comment]
(See Trello board for more information)
