### ISSUE TITLE
Can’t release grade to a student when there is a linked LO

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4249]
### Expected Behavior

You should be able to submit and make a grade visible to a student when there are learning objectives tied to the assignment being graded. 

### Actual Behavior

Currently, I'm not able to do this on staging.

### Steps to reproduce

1. Create an assignment
2. Create an LO
3. Link them
4. Grade a student on that assignment, making sure to make the grade visible to the student. The page hangs here - the "submit" and "submit and grade next" buttons stay greyed out and the page does not advance. 
5. Alternately, you can go to the "grades" tab for that assignment and attempt to release the grade there (assuming the assignment has already been graded and it just needs to be made visible). In this case you'll receive a dialog box warning saying "an error occurred while attempting to release 1 grades".

**Comment by chcholman** [comment]
➤ Michael Skib commented:

maskib check for this on app/umich

**Comment by chcholman** [comment]
➤ Michael Skib commented:

@card this is not happening on umich or app, only staging

**Comment by chcholman** [comment]
➤ Erik Barroso commented:

https://rollbar.com/gradecraft/gradecraft-development/items/4536/ 
possible error

**Comment by chcholman** [comment]
➤ Michael Skib commented:

erikbarroso2 That's exactly the error I saw when this happened, yup!

**Comment by chcholman** [comment]
➤ Michael Skib commented:

I created a new course and tested this bug out there and it DOES NOT happen! :) caitlinholman1 erikbarroso2  Should we archive this card or leave it? I'm torn because it triggered a rollbar error and that gives us something more to investigate.

**Comment by chcholman** [comment]
➤ Erik Barroso commented:

michaelskib This still triggered a roll bar error when it successfully released a grade with a linked learning objective? If thats the case I'd like to just keep it open and have you attach a link to the rollbar error if you find it! Thanks (:

**Comment by chcholman** [comment]
➤ Michael Skib commented:

erikbarroso2 No it fortunately didn't trigger a rollbar error when it successfully released a grade with a linked learning objective, just when it was unsuccessful. Given that it was only unsuccessful in my original testing course, I'd say there's something "broken" about my original testing course, and I'm no longer going to use it for testing purposes. I could try to get to the root of what's causing it to happen in that course, but it seems like that would be a lot of time spent looking for something that's likely a pretty far edge case.

**Comment by chcholman** [comment]
➤ Erik Barroso commented:

michaelskib Nobody puts a course through the wringer like you do! 

Totally agree its not something we want to spend the time looking for, I say we archive this one!

**Comment by chcholman** [comment]
➤ Michael Skib commented:

erikbarroso2 Hey Erik, I looked into this issue a little more and it looks like it's a real bug. The issue is specifically when a student achieves the learning objective during the grading process (e.g. if the count to achieve is 1, and they are marked proficient on that LO for the assignment, this will cause the error. But if the count to achieve is 2, their current count is 0, and  they are marked proficient on the assignment it will work fine)

**Comment by chcholman** [comment]
➤ Michael Skib commented:

Here's the rollbar error that gets triggered when this happens: 

https://rollbar.com/gradecraft/gradecraft-development/items/4536/

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4281
