### ISSUE TITLE
Not getting email notifications for grades released

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4250]
### Expected Behavior

Testing email notifications of assignments getting graded on staging, I would expect that these new grade notifications would arrive in the gc.staging@gmail.com email inbox.

### Actual Behavior

We've seen (Sophia and myself) that these email notifications aren't currently arriving in gc.staging@gmail.com

### Steps to reproduce

1. Grade an assignment for a student in staging. Make sure that the student's email notification settings are set to receive grade email notificaiotns.
2. Check the gc.staging@gmail.com inbox to see whether a notification was sent. Right now, no 
emails are showing up.

**Comment by chcholman** [comment]
➤ Michael Skib commented:

maskib test on app/umich

**Comment by chcholman** [comment]
➤ Michael Skib commented:

@card This is only on staging

**Comment by chcholman** [comment]
➤ Michael Skib commented:

Confirmed that this is still an issue on staging with a new blank course

**Comment by adishy** [comment]
@maskib @ebarroso7 

* This does not appear to be a problem in the local environment, the email notification is delivered using both the old and new email templates. Perhaps this is a problem with the email settings on staging?
