### ISSUE TITLE
No notifications or announcements for group status update (approved/declined etc) or group created

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4251]
### Expected Behavior

Testing email notifications of group creation and group status updates, I would expect that these notifications would arrive in the gc.staging@gmail.com email inbox.

### Actual Behavior

We've seen (Sophia and myself) that these email notifications aren't currently arriving in gc.staging@gmail.com

### Steps to reproduce

1. As a student, create a team on a group assignment. Make sure that the account settings are set up to receive group status related emails.
2. As an instructor, approve the team that was proposed.
3. Check gc.staging@gmail.com to see whether there have been any notifications sent related to the team's status.

**Comment by chcholman** [comment]
➤ Michael Skib commented:

maskib test on app/umich

**Comment by chcholman** [comment]
➤ Michael Skib commented:

This is also an issue on app and umich
