### ISSUE TITLE
Announcements dropdown on the student side is out of sync with the "view all announcements view"

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4253]
### Expected Behavior

The three most recent announcements in the announcements dropdown should be the same as the three most recent announcements on the "view all announcements" page.

### Actual Behavior
They aren't, necessarily. 

### Steps to reproduce

1. Grade an assignment
2. View that student's dashboard. 
3. Click the announcements icon, take note of the three most recent announcements listed there
4. Click the "view all announcements" link
5. Confirm whether the three most recent announcements in this table are the same as the ones in the dropdown.

<img width="1552" alt="Screen Shot 2019-05-13 at 4 58 54 PM" src="https://user-images.githubusercontent.com/38505166/57653886-e513ad80-75a0-11e9-95ad-667ce982e788.png">

**Comment by chcholman** [comment]
➤ Michael Skib commented:

@card Only an issue on staging

**Comment by chcholman** [comment]
➤ Michael Skib commented:

Confirmed the issue persists with a new course

**Comment by ebarroso7** [comment]
for some reason, this issue was not closed when tagged in the PR #4284, so i'm closing it now
