### ISSUE TITLE
It is possible to add an admin staff member to an individual course, but then that admin does not appear in the list of course staff

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#4259]
It is possible to add an admin staff member to an individual course, but then that admin does not appear in the list of course staff.

Steps to reproduce:

1. Go to "https://staging.gradecraft.com/staff"
1. Click "+ new staff member"
1. Add name, email, and select "admin" from the dropdown list of roles.
1. Click "create user"
1. Observe whether the new user has been added to the list of course staff.

┆Attachments: <a href="https://trello-attachments.s3.amazonaws.com/5a6f2020d4ad818ef1fffe12/5cdf0cd379ce3580ee0316dc/7489713fd5baf4089e3c7c62f9df2721/Screen_Shot_2019-05-17_at_3.05.33_PM.png">Screen Shot 2019-05-17 at 3.05.33 PM.png</a>

**Comment by chcholman** [comment]
➤ Michael Skib commented:

This is also an issue on umich and app.

**Comment by adishy** [comment]
Possibly an issue in user.rb > with_role_in_courses (the role list does not include "admin")

**Comment by ebarroso7** [comment]
Hi @chcholman @maskib ! 

I'm a little confused by the use case / functionality of what we're trying to achieve here.

Two things that come to my mind when looking at this are:

If a user gets made an admin on a singular course, they're still treated as an admin throughout the application. This would mean that they have the ability to change things we normally reserve for Evan or Michael to do like delete course memberships, mark the course as paid, turn on learning objectives.

There are 15-20 admins on each course in app/umich so displaying them on this page would add a lot of clutter and confusion to the average staff member. Maybe we only show the full admin list to users that are also admins? 

So I guess my biggest question is when are we creating a staff member thats just an admin in a specific course? Then also, do we want all admins to be displayed in this list?

**Comment by chcholman** [comment]
➤ Caitlin Holman commented:

erikbarroso2 Let's chat about this with Sophia? There are some bugs in this workflow, but I think this might actually not be one of them (leaving admin out of the view was very intentional at the time it was written)

**Comment by chcholman** [comment]
➤ Michael Skib commented:

caitlinholman1 Mind if I join the convo? I think it would be useful for me to understand the desired workflow too

**Comment by chcholman** [comment]
➤ Caitlin Holman commented:

michaelskib Sounds ideal!
