### ISSUE TITLE
Rubric Points Allocated more than Assignment's Points Total

### ISSUE THREAD

**Issue by shaelynalbrecht** [UM-USElab/gradecraft-development#4268]
### Expected Behavior
When first creating an assignment that uses a rubric, the grading tab shows 0/total points allocated, and the statement underneath should say that you haven't allocated any points yet.

### Actual Behavior
When first creating an assignment that uses a rubric, the grading tab shows 0/total points allocated. However, the statement underneath shows that you have allocated all of the points. If you go to add a criterion, the numbers add appropriately, but the statement says you've gone over the points total.

### Steps to reproduce
Create a new assignment with a rubric. Under details, enter how many points the assignment will be worth. Then, go to the grading tab and add criterion with points.

This issue does not exist if you update the assignment with a full points total and then add criterion levels.

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4270
