### ISSUE TITLE
When importing grades from Canvas, sometimes random individual student grades don't get imported.

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#4272]
Feedback from Rebecca:
This was not consistent, but happened frequently enough to be frustrating. They had quizzes in Canvas, and they would import quiz grades into GradeCraft, but it would only import some of them, not all. It was never at a logical cut-off, it would just be random grades missing.

**Comment by chcholman** [comment]
➤ Erik Barroso commented:

comments go through

**Comment by maskib** [comment]
Deep dive required. With ahoy tracking. Good spring cleanup item.
