### ISSUE TITLE
Clarify that "Open Date" is an optional field

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#4276]
Feedback from Rebecca:
For Dates on the Details tab for an Assignment: Wasn’t clear that “Open Date” for assignments is not required. For a while, she was always entering the Open Date for assignments because she thought she had to. She didn’t realize it was okay to leave it blank.

**Comment by maskib** [comment]
Hopefully addressed in the instructor-facing assignment setup redesign; have added info/helper text from Holly
