### ISSUE TITLE
Evaluate position and look of "Delete All Grades" button

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#4277]
Feedback from Rebecca:
On Grading tab for an assignment: She was perplexed by why the Delete All Grades button was located there. Being bright pink and in the top right of the screen, it feels too easy to just click, which she felt was dangerous.

┆Attachments: <a href="https://trello-attachments.s3.amazonaws.com/5a6f2020d4ad818ef1fffe12/5ce8061951a44c5ac4a0cac2/dcd443290c1de3bd3914419f55051736/delete_all_grades.png">delete all grades.png</a>

**Comment by maskib** [comment]
In Sophia's stretch (Winter 2020) goals for the redesign, on her radar.
