### ISSUE TITLE
Going to the "analytics" page in an unpublished course leads to a server error

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4289]
<img width="1464" alt="Screen Shot 2019-06-03 at 2 49 46 PM" src="https://user-images.githubusercontent.com/38505166/58826508-dc961c00-860e-11e9-9967-cbe164f853c2.png">

### Expected Behavior
Either there wouldn't be an analytics link for an unpublished course, or it would go to a blank page, with some sort of notification stating that content will display once the course starts.

### Actual Behavior
Going to the "analytics" page in an unpublished course leads to a server error.

### Steps to reproduce
1. In a course that hasn't been published, click "analytics" in the left nav.

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4293
