### ISSUE TITLE
Page not found error when clicking link to a badge that is an unlock condition on an assigment

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4290]
### Expected Behavior
Clicking the link to see a badge that is set to be the unlock condition on an assignment should take you to the badge itself.

### Actual Behavior
Clicking the link to see a badge that is set to be the unlock condition on an assignment triggers a "page not found" error.

### Steps to reproduce
1. Create an assignment, with a badge as the unlock condition. You will be testing as a student in the next step, so make sure it's a badge that this student hasn't earned yet.
2. As a student, view that assignment. You should see something like this:
<img width="1552" alt="Screen Shot 2019-05-31 at 11 10 12 AM" src="https://user-images.githubusercontent.com/38505166/58826750-6219cc00-860f-11e9-83af-7d1d765d00bc.png">
3. Click the link to the badge. You should get an error like this: 
<img width="1552" alt="Screen Shot 2019-05-31 at 11 10 34 AM" src="https://user-images.githubusercontent.com/38505166/58826778-71991500-860f-11e9-98ff-2b8e9d4df3e2.png">

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4292
