### ISSUE TITLE
No empty state for "assignment analytics" page

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4291]
### Expected Behavior
I would expect some kind of "empty state" content for the assignment analytics page when there's nothing to display

### Actual Behavior
Currently the page is blank

### Steps to reproduce
1. In a course where there's not enough data to display assignment analytics (no assignments with more than 1 student graded on it), click "analytics" in the left nav. 
2. Select "assignment analytics from the drop-down menu in the upper right hand corner. (this is the default but I'm adding it as a step just to be clear). You'll see something like this: 
<img width="1552" alt="Screen Shot 2019-05-31 at 11 10 12 AM" src="https://user-images.githubusercontent.com/38505166/58827176-5b3f8900-8610-11e9-8045-de9441737188.png">

**Comment by sophiazumich** [comment]
@maskib I haven't been able to address this issue yet; should it really be closed?

**Comment by adishy** [comment]
@sophiazumich The pull request referenced did add a default message for the page that says something along the lines of "Add an assignment to see analytics". 
Of course, I can reopen the issue if required

**Comment by sophiazumich** [comment]
@adishy I will defer to @maskib if he thinks we should reopen this, since I think he logged it for me (I think we came across it when doing the email testing together)

**Comment by adishy** [comment]
@sophiazumich @maksib Alright, I'll reopen the issue for now, and we can close this as per whatever we decide later :)

**Comment by maskib** [comment]
@adishy Thanks! The idea is that we'll leave issues open until they've been tested by somebody other than the person(s) who worked on the code - either myself, Evan, Cait, etc. 

I just took a look at this - I would recommend changing the text slightly. Currently: 
"There are currently no assignment types for this course, add an assignment type and then create assignments to see analytics."

Possibly change to:
"There are currently no assignments in this course; add an assignment to see analytics."

The comma should either be a period or a semicolon, and I thought it might be confusing to have the text be about how there are no assignment types. There's a separate analytics page about assignment types. 

Also, once you create assignment, if there are no grades in the course yet, that default message for the empty state disappears.

**Comment by chcholman** [comment]
➤ Michael Skib commented:

https://github.com/UM-USElab/gradecraft-development/pull/4318
