### ISSUE TITLE
Removing a staff member who is a team leader from a course does not also remove them from their team

### ISSUE THREAD

**Issue by adishy** [UM-USElab/gradecraft-development#4308]
### Expected Behavior
* When removing a staff member from a course, if they are a leader for a team in the course, they should also be removed from the team.

### Actual Behavior
* Currently, removing a staff member from a course who is a leader for a team does not remove them from their team.

### Steps to reproduce
* As an admin, create a staff member and assign them as the leader for a team
* Delete the staff member
* When viewing all the teams in the course (i.e. /teams), the staff member who was removed is still listed under the "TA" column with their team.

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4304
