### ISSUE TITLE
"Grade" button styling is slightly different for group assignment submissions vs. individual assignment submissions

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4309]
### Expected Behavior
Looking at the instructor "Grading status" page, all "grade" buttons would have the same styling, regardless of what type of assignment it is. 

### Actual Behavior
Looking at the instructor "Grading status" page, group assignment submission "grade" have a slightly different styling.

### Steps to reproduce
1. Create 2 assignments, both accepting submissions, one for individuals and one for a group. 
2. With a student, submit to the individual assignment and propose a team for the group assignment.
3. As an instructor, approve the group.
4. As the student, submit to the group assignment. 
5. As an instructor, navigate to the grading status page and check out the "grade" buttons.

<img width="1552" alt="Screen Shot 2019-06-07 at 9 57 59 AM" src="https://user-images.githubusercontent.com/38505166/59109480-1f0b7180-890b-11e9-80fb-4ae58cd32fe6.png">

**Comment by chcholman** [comment]
➤ Sophia Zhou commented:

Style bug seems to be in submissions.html.haml 
All other <a> had the class "button" except for the snippet regarding Grade Group Assignments. How they all have the .button class and hopefully this will fix it.
