### ISSUE TITLE
When awarding a badge while grading an assignment, it should be possible to provide badge feedback

### ISSUE THREAD

**Issue by adishy** [UM-USElab/gradecraft-development#4314]
### Expected Behavior
* When awarding a badge while grading an assignment as an instructor, it should be possible to provide badge feedback for the awarded badge.

### Actual Behavior
* Currently there is no way to provide badge feedback for the awarded badge.

### Steps to reproduce
* As an instructor, grade an assignment and award a badge. It is not possible to provide badge feedback for the awarded badge.

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4313
