### ISSUE TITLE
It should be possible to export a specified date range for certain course data export types

### ISSUE THREAD

**Issue by adishy** [UM-USElab/gradecraft-development#4315]
### Expected Behavior
* For some courses such as the Talent Gateway Online Community course, the ability to export assignment submissions within a specified date range is required.

### Actual Behavior
* Currently, this is not possible and exporting assignment submissions will export all assignment submissions from the creation of the course, which is not required.

### Steps to reproduce
* Visit the /downloads page as an instructor. It is not possible to specify a date range for exporting the assignment submissions course export type.

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4310

**Comment by chcholman** [comment]
➤ adishy commented:

This requires that the course ID is 110, which is the ID for the Talent Gateway Online Community course, however this might cause problems for testing on staging.

**Comment by chcholman** [comment]
➤ Michael Skib commented:

adishy1 Actually, I was able to access an older version of the talent gateway with the same course ID on staging and see the date picker!

**Comment by chcholman** [comment]
➤ adishy commented:

michaelskib That's great!

**Comment by adishy** [comment]
@maskib @ebarroso7 
Testing Suggestions:
* One concern for this PR is input validation / processing. The user should not be able to cause an error in the service by entering a badly formatted / invalid date. Currently, the page does not report errors if the input is bad and continues to produce the most sensible output based on what the user entered. 
Here are a few possibilities for the combinations of start and end date inputs:
* **User specifies neither start date nor end date:** The emailed CSV contains all submissions from the start of the course until the date of the latest submission
* **User specifies start date but not end date:** The emailed CSV contains all submissions from the start date specified by the user until the date of the latest submission
* **User specifies end date but not start date:** The emailed CSV contains all submissions from the start of the course until the date specified by the user.
* **User specifies both start and end dates:**
     * **Both start and end dates are valid:** The emailed CSV contains all submissions from the start date specified by the user until the end date specified by the user. 
    * **Both dates are valid by themselves but the range they specify is invalid**:
         * Possible cases are: 
            * Start date after end date
            * End date after start date 
        * The emailed CSV contains no submissions in both cases.

**Comment by maskib** [comment]
@ebarroso7 @adishy Export does not appear to send if one of the date fields for the date range is left blank.

**Comment by chcholman** [comment]
➤ Michael Skib commented:

@card Export does not appear to send if one of the date fields for the date range is left blank.

**Comment by chcholman** [comment]
➤ Michael Skib commented:

@card In progress until Sophia's styling is applied

**Comment by chcholman** [comment]
➤ adishy commented:

Sophia's styling should now be applied on staging, and the exports should now continue regardless of whether an invalid date is entered.

**Comment by maskib** [comment]
This looks good! In the future this could be improved by adding validation on the dates selected to make sure that dates are valid and the end date is after the start date. Also, there is no "submitted by" column in the CSV so adding that or changing the wording next to the dropdown ("Choose which column the date range is applicable to:") might also be helpful.
