### ISSUE TITLE
It should be possible to add a new user to a team during creation

### ISSUE THREAD

**Issue by adishy** [UM-USElab/gradecraft-development#4317]
### Expected Behavior
* When creating a new user as an admin, it should be possible to add the new user to a team as they are being created.

### Actual Behavior
* Currently, to add a new user to a team, the /teams page must be visited separately and the desired team must be edited.

### Steps to reproduce
* As an admin create a user. It is not possible to add the new user to a team when they are being created.

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4304
