### ISSUE TITLE
Student View: on the badges page, badge information on the right hand side of the window appears broken (see screenshot)

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4325]
### Expected Behavior
Footer should display at the bottom of the page and not show up on top of the page contents. 

### Actual Behavior
The issue appears to be that the page footer is overlapping with the "student-panel-article" on the right side of the page, and the student-panel-article has no background. The footer is also not at the bottom of the page. It is at the bottom of the "badge-index-section" div but the height of that student-panel-article is greater than badge index section. 

### Steps to reproduce
1. Log in as a student to a course with badges. It's easier to see with a course where there are only a handful of badges.
2. Click the "badge" tab and look at the right side of the page:
![Screen Shot 2019-06-25 at 11 01 19 AM](https://user-images.githubusercontent.com/38505166/60110578-4c915100-973a-11e9-9941-92e4df7b0882.png)

**Comment by adishy** [comment]
@maskib this issue should be fixed currently on staging! The page footer was overlappng due to the position property in the style for the sidebar being set to fixed instead of relative
![image](https://user-images.githubusercontent.com/33792934/60343026-0a0d8580-9981-11e9-9d21-18ff9890a69f.png)
