### ISSUE TITLE
Learning objectives should be copied when copying a course with learning objectives turned on

### ISSUE THREAD

**Issue by adishy** [UM-USElab/gradecraft-development#4326]
### Expected Behavior
* When copying a course with learning objectives enabled, the learning objectives in the course should be copied over to the new course, along with any learning objective levels and linked assignments.

### Actual Behavior
* Currently, copying a course with learning objectives does not copy over the learning objectives in the course.

### Steps to reproduce
* As an admin, copy a course with learning objectives
* Visit the learning objectives page (i.e. /learning_objectives/objectives). The learning objectives from the original course are not listed in the current copy of the course.

**Comment by adishy** [comment]
## Suggestions for testing:
  ### Making sure learning objectives are copying correctly:
    * All categories should be copied correctly
    * All learning objectives in each category should be copied over
    * There should be no duplicate categories or learning objectives in the original course
    * Learning objectives without any category should be copied over and be listed under the "Uncategorized" section in the learning objectives page (i.e. /learning_objectives/objectives)
    * Every level within a learning objective should be copied over, along with the name of the level, the description and the competency level. The levels can be viewed by editing a learning objective.
    * Linked assignments in a learning objective should be copied correctly. The linked assignments can be viewed in the learning objective edit page as well as the landing page for a learning objective (i.e. /learning_objectives/objectives/\<id\>)
    * Learning objective categories, learning objectives, learning objective levels and linked assignments with identical names, descriptions, count to achieve, points to achieve and other attributes should be copied over correctly with their relative associations retained in the copy.

  ## Making sure existing functionality is unaffected:
    * Copying a course without learning objectives should not be affected.
    * Copying a course with learning objectives along with the students currently in the course (the "Copy + Students" option in the option dropdown) should not be possible.
    * Copying a course with learning objectives should copy over all other course attributes such as assignment types, assignments etc. as expected.
    * It should be possible to award a learning objective to a student
    * It should be possible to view a learning objective as a student and instructor
    * Unlock conditions on assignments that are linked to learning objectives should apply. (i.e. if an assignment is not visible to students, it should not appear in the list of linked assignments when viewing the learning objective as a student)
    * Deleting a learning objective should work normally
    * It should be possible to add, remove and edit learning objective categories, learning objectives and learning objective levels

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4324

**Comment by adishy** [comment]
## Suggestions for testing:
  ### Making sure learning objectives are copying correctly:
   - [ ]  All categories should be copied correctly
   - [ ]  All learning objectives in each category should be copied over
   - [ ]  There should be no duplicate categories or learning objectives in the original course
   - [ ]  Learning objectives without any category should be copied over and be listed under the "Uncategorized" section in the learning objectives page (i.e. /learning_objectives/objectives)
   - [ ]  Every level within a learning objective should be copied over, along with the name of the level, the description and the competency level. The levels can be viewed by editing a learning objective.
   - [ ]  Linked assignments in a learning objective should be copied correctly. The linked assignments can be viewed in the learning objective edit page as well as the landing page for a learning objective (i.e. /learning_objectives/objectives/\<id\>)
   - [ ]  Learning objective categories, learning objectives, learning objective levels and linked assignments with identical names, descriptions, count to achieve, points to achieve and other attributes should be copied over correctly with their relative associations retained in the copy.

  ### Making sure existing functionality is unaffected:
   - [ ]  Copying a course without learning objectives should not be affected.
   - [ ]  Copying a course with learning objectives along with the students currently in the course (the "Copy + Students" option in the option dropdown) should not be possible.
   - [ ]  Copying a course with learning objectives should copy over all other course attributes such as assignment types, assignments etc. as expected.
   - [ ]  It should be possible to award a learning objective to a student
   - [ ]  It should be possible to view a learning objective as a student and instructor
   - [ ]  Unlock conditions on assignments that are linked to learning objectives should apply. (i.e. if an assignment is not visible to students, it should not appear in the list of linked assignments when viewing the learning objective as a student)
   - [ ]  It should be possible for a learning objective to be an unlock condition for an assignment and the equivalent assignment in the copied course should list the learning objective as an unlock condition.
   - [ ]  Deleting a learning objective should work normally
   - [ ]  It should be possible to add, remove and edit learning objective categories, learning objectives and learning objective levels
    
----

..and anything more you can think of!
