### ISSUE TITLE
Self-logged grades and grade levels: no option selected bug

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4335]
### Expected Behavior
Note: this relates to self-logged assignments with grade score levels. As a student, if I don't select an option from the dropdown list of grade score levels, but I click "submit", I would expect nothing to happen, or for a modal to pop up prompting me to select an option.

### Actual Behavior
If you don’t select anything from the dropdown menu of grade levels, you are automatically awarded full points on the assignment when you click “submit” (even when that’s not one of the options in the dropdown menu!)

### Steps to reproduce
1. Create an assignment that is self-logged and has grade score levels. 
2. Log in as a student, and click on that assignment. 
3. Without selecting anything from the dropdown list (it should read "select your outcome"), click "submit"

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4337
