### ISSUE TITLE
Learning objectives not showing on assignment's grade page 

### ISSUE THREAD

**Issue by ebarroso7** [UM-USElab/gradecraft-development#4341]
### Expected Behavior
If you grade an assignment with a learning learning objective you would expect some reference to the learning objectives on the specific assignments grade page. 

### Actual Behavior
Currently an instructor does not see anything on the grade page regarding the learning objective associated with the assignment. 

### Steps to reproduce

Grade an assignment with a learning objective, award some level of proficiency towards the objective, then go back to the grade page for that assignment and nothing will be visible regarding the learning objective.

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4344
