### ISSUE TITLE
Feedback for learning objective levels not saving

### ISSUE THREAD

**Issue by ebarroso7** [UM-USElab/gradecraft-development#4342]
### Expected Behavior
If you grade a learning objective and give feedback for the level of proficiency that the student was awarded, that feedback should be saved and visible to the student and instructor. 

### Actual Behavior

comments would save during grading of a learning objective.

learning_objective_observed_outcomes comments are not being saved or displayed properly.

### Steps to reproduce
👆

┆Attachments: <a href="https://trello-attachments.s3.amazonaws.com/5a6f2020d4ad818ef1fffe12/5d376c779b61f001a7d62a15/096b9e0ee6cc8f43978c7767d53aaf80/LO_Comments_not_saving_bug_testing_notes_090519_.rtf">LO Comments not saving bug testing notes 090519 .rtf</a> | <a href="https://trello-attachments.s3.amazonaws.com/5a6f2020d4ad818ef1fffe12/5d376c779b61f001a7d62a15/496276fbb392915c154e29cb548d6851/Screen_Shot_2019-09-05_at_5.36.08_PM.png">Screen Shot 2019-09-05 at 5.36.08 PM.png</a>

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4345

**Comment by chcholman** [comment]
➤ Michael Skib commented:

@card Currently investigating this. I'm noticing that there are some conditions in which LO feedback does not save when you click "submit grade", but I haven't been able to figure out yet what causes this.

**Comment by chcholman** [comment]
➤ Michael Skib commented:

@card Below I added browser console output (Thank you, Rollbar!!!) showing current values for one LO outcome that saved comments, and one that wouldn't save any comments, despite multiple attempts (the second one)
