### ISSUE TITLE
Course analytics export rebuild

### ISSUE THREAD

**Issue by ebarroso7** [UM-USElab/gradecraft-development#4343]
### Related Issues with Course Analytics export 

https://github.com/UM-USElab/gradecraft-development/issues/1631
https://github.com/UM-USElab/gradecraft-development/issues/1632

### Actual Behavior

Currently, course exports analytics are turned off. they are not displayed in the `views/downloads/index.html.haml` file on line #49 the option to generate them has been turned off. 

This issue was rediscovered in the transition from AWS --> Openshift specifically the s3 file uploads seen here in this PR: https://github.com/UM-USElab/gradecraft-development/pull/4333 

When comments are take out, the export is still not generated

**Comment by maskib** [comment]
@ebarroso7 Can you clarify which export this refers to? In https://github.com/UM-USElab/gradecraft-development/blob/master-efs/app/views/downloads/index.html.haml" I'm not seeing anything called "course analytics exports" or anything related to analytics, per se.

**Comment by ebarroso7** [comment]
@maskib Looks like it was removed here: https://github.com/UM-USElab/gradecraft-development/commit/3616041ad9e5d0899573cb24aacd69c43e793e8d#diff-46244718f28168dabf5602394bdeafe7 

```
#%tr
        #  %td= link_to glyph("file-excel-o") + "Course Analytics", course_analytics_exports_path, method: :post
        #  %td Event data including pageviews, predictions, and logins
```
is the comment out code

**Comment by maskib** [comment]
Needs to be completely rebuilt - feature, not a bug.
