### ISSUE TITLE
Users page - seeing a student's sections from other courses but can't access them from this page [Check again after TLD]

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4348]
### Expected Behavior
I would expect that if we're going to show all of the sections that a user is in across all courses on the "current course users" page, and if they're clickable, that we would be able to access those course sections directly by clicking the name.

### Actual Behavior
If you click on the name of a section that isn't in the course you're currently in, you get a 404 yeti error.

### Steps to reproduce

1. Create a student, enroll them in two courses.

2. Create sections in both courses and add the student to both sections.

3a. (If you want to skip those steps, just go to https://staging.gradecraft.com/courses/1007/edit and then click the "current course users" button.)

3b. In one of the courses, click the "current course users" button. 

4. In the table on that page, click the name of the section that user is in that is not part of the course you're currently in. 

5. YETI

**Comment by ebarroso7** [comment]
This is an admin page so very low priorities. We will have to find a way to get around things like this for the top level dashboard page - trying to get into something that is outside of your `current_course`
