### ISSUE TITLE
Maybe we should consider changing the default value of "Allows Canvas?" in course admin settings for app

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4349]
### Expected Behavior
It sounds based on a conversation with Evan and James A. that we should change the default value of "allows canvas?" in the admin settings of the course settings page, just on app, because we don't actually allow connection to canvas by default, and we have to work with the institutions directly to get that set up. 

To sum up, we want the default value for "allows canvas?" to be "no", aka "unchecked".

### Actual Behavior
When a new course is created in app, the "allows canvas?" box is checked by default.

**Comment by ebarroso7** [comment]
Added this in the PR: https://github.com/UM-USElab/gradecraft-development/pull/4434 

Did not know this issue was filed so i'm closing it now
