### ISSUE TITLE
Remove "username" field from the student import template .csv

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4374]
Because we aren't using the username field to generate usernames (we're using the first portion (before the @ sign) of email addresses), we would like to remove that column from the .csv template for importing students to reduce unnecessary confusion for our users.

**Comment by chcholman** [comment]
➤ Michael Skib commented:

https://github.com/UM-USElab/gradecraft-development/pull/4388

**Comment by chcholman** [comment]
➤ Michael Skib commented:

adishy1

Currently, using this file to import users isn't working. Is this because the import still expects there to be usernames for the students in the .csv?
