### ISSUE TITLE
Badge Timestamp displaying GMT instead of users timezone 

### ISSUE THREAD

**Issue by ebarroso7** [UM-USElab/gradecraft-development#4384]
### Expected Behavior
The badges awarded at time would display according to the users timezone and not in GMT. 

### Actual Behavior
![image](https://user-images.githubusercontent.com/43551022/65710363-df56ca00-e060-11e9-8762-e1dd1f05f348.png)

^ Screenshot submitted by Laurie, saying that  " I noticed that the time stamp was off by 4 hours - see attached." 

### Steps to reproduce

Not quite sure what page this is on, but she also mentioned that it was an auto awarded badge.

**Comment by ebarroso7** [comment]
Looks like this is seen on the specific badge page `/badges/<badge_id>/`

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4385

**Comment by maskib** [comment]
The ideal fix for this would be to remove the timestamp from the text comment string and make it a new variable on the badge for when it was awarded - add a boolean flag for auto awarded on the earned badge. Don't need to worry about retroactively fixing (removing) timestamp from earned badge comment box
