### ISSUE TITLE
New announcements not being added to the announcements table until you leave the course and return

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4386]
### Expected Behavior
When you send a new announcement, I would expect that it would be added to the table on the https://app.gradecraft.com/announcements page. 

### Actual Behavior
It is not added. You have to leave the course and then return to the course, then you will see the announcement in the table. 

### Steps to reproduce
1. Create a new announcement. Take note of the title of that announcement
2. Check the table on https://app.gradecraft.com/announcements for the announcement. You should see that it was not added. 
3. Leave the course, go to another course. 
4. Return to the original course, and look at the assignments table. You should now see it there.

**Comment by adishy** [comment]
@maskib @ebarroso7 
* This issue looks like a problem related to caching the list of announcements displayed within the view. When a new announcement is created, it does not show up in the list of announcements but it is created. The new announcement can be accessed by essentially guessing the id of the announcement by adding 1 to the id of the latest announcement and accessing it on the announcement display page (i.e. /announcements/\<id\> (of course, there is no guarantee that this technique will always work, but it should work for quickly testing this on staging when there is only one user creating the announcements). 
* The issue appears to be in views/announcement/_list.html.haml, which seems to cache the announcements in the course. 
* Currently, caching the announcements has been removed from the announcements age (i.e. /announcements) on staging, but to see changes, you might have to clear site data for staging or open staging in a private window in your browser and then create a new announcement.
