### ISSUE TITLE
An instructor cannot delete an individual student's self-logged grade

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4390]
### Expected Behavior
When an instructor looks at a self-logged grade for a student, there is a button that says "delete self-logged grade". This should delete the grade. 

What's odd too is that while it's not possible for an instructor to delete an individual student's grade on a self-logged assignment, it is possible for them to delete all of the grades for a self-logged assignment by clicking the "delete all grades" button on the assignment details page.

### Actual Behavior
When you click the "delete self-logged grade" button, the grade is not deleted; instead, you are taken to the course dashboard page and shown an error message in pink reading "Please login first".

### Steps to reproduce
1. Create a new self-graded assignment
2. With a dummy student, mark that you've completed the assignment
3. As an instructor, view that student's grade for the assignment.
4. Click "delete self-logged grade" button.

**Comment by chcholman** [comment]
➤ adishy commented:

https://github.com/UM-USElab/gradecraft-development/pull/4391
