### ISSUE TITLE
Multipliers: When setting up a course, enabling multipliers is an option, but it doesn't work

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4392]
### Expected Behavior
Setting up multipliers in a course should be possible at any point where the option is provided. Any errors related to setting up multipliers would be clear and meaningful to users.

### Actual Behavior
At the beginning of the course setup process, you can turn on the multipliers feature. However, if you do so, you won't be able to create your course, and you'll receive an error that says "full points must be set to greater than 0 for the multipliers feature to work properly." 

<img width="1295" alt="Screen Shot 2019-10-17 at 10 57 37 AM" src="https://user-images.githubusercontent.com/38505166/67021349-7dbcd500-f0cd-11e9-9982-7392bde6e037.png">

### Steps to reproduce

1. Create a new course
2. Enable multipliers
3. Click "create course"

**Comment by ebarroso7** [comment]
Courses are having trouble being created when multipliers are set due to this course validation: 
`validates_numericality_of :total_weights, :max_weights_per_assignment_type, :full_points,
    :max_assignment_types_weighted, less_than_or_equal_to: 999999999, greater_than: 0, if: lambda { self.has_multipliers? }, message: "must be set to greater than 0 for the Multipliers feature to work properly."` 

when the `:full_points` argument is removed, a course can be created without multipliers

**Comment by ebarroso7** [comment]
commit 4fb2e435e1580b14 removes full_points fun this validation because it is now being used to address the progress bar visualization on the course dashboard
