### ISSUE TITLE
At certain screen widths, the "class info" button and "switch course" field get misplaced. 

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4394]
### Actual Behavior
At certain window widths (about 1050px) , the "class info" button and "switch course" field get misplaced, overlapping on top of the clickable tabs in the light blue bar underneath it.
<img width="1217" alt="Screen Shot 2019-10-17 at 11 58 07 AM" src="https://user-images.githubusercontent.com/38505166/67026968-cb8a0b00-f0d6-11e9-87ae-36e1526001e2.png">

### Steps to reproduce
1. Narrow your screen to about 1050px and you should see something like the screenshot above.

**Comment by ebarroso7** [comment]
https://github.com/UM-USElab/gradecraft-development/commit/5f0d7421610cfef09ab01543608e6c4d27b2a880 

closes this (for now, still can happen but better than it was) 

will be resolved when we add a new nav from vue
