### ISSUE TITLE
Announcement Alert Box Orders (Unread before Newest Read Announcement)

### ISSUE THREAD

**Issue by heybigjoy** [UM-USElab/gradecraft-development#4408]
### Expected Behavior
Unread messages will show in the announcement alert box. 

### Actual Behavior
![](https://files.slack.com/files-pri/T0EE3U0T0-FQ93JLU7N/screen_shot_2019-11-07_at_10.16.58_am.png)
The newest announcements will always be shown in the announcement box even they have been read. 

### Steps to reproduce
Create announcements and view as a student, new announcement will not go away after they've been read. 
I would expect an older unread announcement to show in the alert box.

**Comment by heybigjoy** [comment]
<img width="442" alt="Screen Shot 2019-11-07 at 10 16 58 AM" src="https://user-images.githubusercontent.com/46545572/68409294-d32c5500-0154-11ea-88f4-fd743748785d.png">

**Comment by maskib** [comment]
Feature request. In UXR testing of student-facing course dashboard redesign, regarding announcement notification, students didn't feel particularly strong about getting the current initial dropdown or going directly to the Announcements page. Given that, perhaps a solution would be to continue having the "red dot" alert when you get new notifications, and clicking the icon will simply take you directly to the Announcments page, which has a table view of all announcements.
