### ISSUE TITLE
When grading with a rubric, in one case the "submit grade" and "submit and grade next" buttons become unclickable

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4422]
### Expected Behavior
If you do not select a level for any criterion in your rubric, and then click either "submit grade" or "submit and grade next", you'll be prompted with a warning letting you know this was the case. You can either click ok or cancel on that warning. If you click cancel, nothing should change about the rubric grading page and you should still be able to submit the grade later. 

### Actual Behavior
If you click "cancel" on the popup warning described above, the "submit grade" and "submit and grade next" buttons become unclickable.
<img width="1261" alt="Screen Shot 2019-12-13 at 12 02 18 PM" src="https://user-images.githubusercontent.com/38505166/70818228-3424f980-1da1-11ea-87f4-66b086ad82a0.png">

### Steps to reproduce
1. Grade a student on an assignment with a rubric. 
2. Do not provide a grade on at least one criterion
3. Click "submit grade"
4. Click "cancel" on the warning that pops up.

**Comment by maskib** [comment]
@ebarroso7 Hey Erik, any chance this could be pushed soon? We have another faculty member who's reported issues related to not being able to submit and submit and grade next and I suspect this may  be connected to that.

**Comment by adishy** [comment]
@ebarroso7 @maskib Just pushed this to staging in case this is urgent!

**Comment by maskib** [comment]
@ebarroso7 @adishy Hey guys, I just wanted to check and make sure this got merged to umich and app? We got another bug report of an issue similar to this so I just wanted to check. Thank you!
