### ISSUE TITLE
It seems like there might be missing styling on the "grade assignment by rubric" header

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4424]
It seems like there might be missing styling on the "grade assignment by rubric" header. It is expandable and collapsible but doesn't have the same styling as the other expandable/collapsible elements on the page. Nothing currently indicates that you can expand and collapse that section. 
<img width="1261" alt="Screen Shot 2019-12-13 at 12 37 28 PM" src="https://user-images.githubusercontent.com/38505166/70820023-9f70ca80-1da5-11ea-92d0-891e2300965d.png">

**Comment by sophiazumich** [comment]
@maskib and @ebarroso7, I just edited a number of files related to this. For record keeping, Michael and I decided to make the "Grade Assignment with Rubric" bit consistent with the other arrow-toggle accordions. While I was addressing this page, I also did some class clean-up, typographical hierarchy updates, and a wee SASS refactor. The changes are committed so we should see them in the next build! 

<img width="1391" alt="Screen Shot 2019-12-13 at 2 33 45 PM" src="https://user-images.githubusercontent.com/40248497/70826735-a99ac500-1db5-11ea-8c59-ff5c28c635f2.png">
<img width="1391" alt="Screen Shot 2019-12-13 at 2 34 00 PM" src="https://user-images.githubusercontent.com/40248497/70826737-aacbf200-1db5-11ea-9dcd-4115ebc49acd.png">
