### ISSUE TITLE
"404" page still uses old favicon

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4425]
<img width="1261" alt="Screen Shot 2019-12-13 at 12 23 26 PM" src="https://user-images.githubusercontent.com/38505166/70820090-caf3b500-1da5-11ea-9055-5549289efab1.png">

There might be others out there as well that use the old one.

**Comment by sophiazumich** [comment]
@maskib I just updated error pages for 404, 422, and 500, as well as 2 HAML files for error.html.haml and public.html.haml that were still rendering the old favicon. Hopefully, when @ebarroso7 next runs a build, these will be fixed!
