### ISSUE TITLE
Group assignments (instructor-facing): If a group has received a grade on a pass/fail assignment, if you click on the "Grades" tab the page won't load, and there will be console errors

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4461]
Similar to https://github.com/UM-USElab/gradecraft-development/issues/4460, but this one is not fixed by a hard reset and persists. 

<img width="1262" alt="Screen Shot 2020-02-20 at 4 48 23 PM" src="https://user-images.githubusercontent.com/38505166/74981941-2cb54880-5401-11ea-9b35-53cb1ed7109c.png">

1. Create a group assignment with a pass/fail grade.
2. Set up a group to complete an assignment
3. Grade that group on that assignment
4. Click the "assignments" page in the left nav
5. Click on the assignment in the list of assignments
6. Click the "grades" tab

This one happens every time this issue happens - https://rollbar.com/gradecraft/gradecraft-development/items/4305/

This one is specific to a group assignment with a pass/fail grade status - https://rollbar.com/gradecraft/gradecraft-development/items/3434/

**Comment by ebarroso7** [comment]
fixed with commit 6120d3438b9f6c4444159232c (cherry-picked into production)
