### ISSUE TITLE
Multiple submissions

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#875]
As a student, I need to be able to submit an assignment, receive a grade, and then re-submit the assignment with revisions. These submissions should both be preserved - as an instructor and student I want to be able to see the progress between iterations.

**Comment by jwright** [comment]
@chcholman Is the extent of this feature to just provide the database/storage mechanism or is there going to be some UI involvement?

If there is some UI involvement, can a student just view their multiple submissions one at a time or are we providing them with a diffing/comparison UI feature at this time?

**Comment by chcholman** [comment]
There should be some UI involvement. To lay out the aspects (and I'm going to describe the process of submissions broadly):  

1) Up until the due date OR until I receive a grade, I should be able to freely edit my submission. I'm open to the idea that we could treat it like a wiki, and document every change - that may actually be the easiest way as opposed to making sense of which change precisely to track. 

2) If I submit something after the due date, both the instructor and I need to see it marked as late (this will have point repercussions later, right now the instructor is expected to notice and mark down things that are late). 

3) If I receive a grade, and the assignment accepts resubmissions, then I should be able to create a truly distinct submission from my first - different files associated, different content, and (here's the big thing) a different grade. Ideally, we'll be able to store both grades (both in rubric form or standard form) but _only count the one that is associated with the latest submission_ towards the student's grade. 

4) On both the student and instructor side, if they navigate to the submission history for an assignment, they should see the details regarding their assignments, including what has been submitted, when, and what grade it's received. 

5) On the instructor side, resubmissions should marked as such (they're a very different thing to grade) and appear in their own category on the "Grading Status" page, and the "Resubmissions" page (the longterm goal is to remove the "Resubmissions" and "Ungraded Submissions" pages - they're only present because we've had a hard time getting the Grading Status page to be efficient throughout the semester with large classes).

**Comment by jwright** [comment]
@chcholman This may be a good use for using [PaperTrail](https://github.com/airblade/paper_trail). 

I have used it before on another project and it is really nice. Any thoughts on it?

**Comment by jwright** [comment]
- [ ] Ensure that the late functionality works and is tested well

**Comment by jwright** [comment]
I am closing this ticket as it has been broken out into additional tickets which have been related to this one.
